import type { ReactNode } from 'react';
import type { VisualizationProps } from '@/visualization/registry';
import { Compare } from './philKit';

/**
 * The easy problems beside the hard one.
 *
 * "Easy" is Chalmers's own word and it is ironic — each left-hand entry is a
 * career's work. The figure has to convey that the difference is in kind, not
 * in difficulty, which is why the columns are labelled by what a solution would
 * look like rather than by how hard they are.
 */
export default function HardProblemGap(_props: VisualizationProps): ReactNode {
  return (
    <Compare
      label="Two kinds of question about the mind — a conceptual comparison"
      leftTitle="Answerable by a mechanism"
      rightTitle="Not obviously answered by one"
      gap
      rows={[
        {
          id: 'discriminate',
          left: 'How does the brain tell red from green?',
          right: 'Why is there something it is like to see red?',
          detail:
            'The left question has a real answer involving receptors and opponent processing. Having that answer in full seems to leave the right-hand question exactly where it was.',
        },
        {
          id: 'attention',
          left: 'How is attention directed and switched?',
          right: 'Why is attending accompanied by experience?',
          detail:
            'A complete account of the mechanism would describe a system that selects, sustains and switches. Chalmers\u2019s question is why that selecting is felt from inside rather than done in the dark.',
        },
        {
          id: 'report',
          left: 'How does a system report its own states?',
          right: 'Why are the reports about anything?',
          detail:
            'Self-monitoring is engineerable. This row is the sharpest, because the reports are the only evidence we have — which is also the deepest problem with settling the question.',
        },
        {
          id: 'status',
          left: 'These are being answered',
          right: 'This is disputed at the root',
          detail:
            'Some hold the gap is real and permanent, some that it will close as neuroscience matures, and some that it is generated by a confusion in how we think about our own states. There is no consensus, and claiming one in either direction would misrepresent the field.',
        },
      ]}
    />
  );
}
