/**
 * The shared reference pool — seed set.
 *
 * These are the primary sources the first content phases will lean on. The pool
 * is intentionally small right now: it exists to prove the citation machinery
 * end-to-end, not to pre-empt the content work. Every entry below is a real,
 * published source; nothing here is a placeholder.
 *
 * Adding a reference: append a record, keep the id stable forever (ids appear in
 * saved links and review notes), and fill `supports` so a reviewer can check the
 * citation without reading the whole paper.
 */
import { referenceId, type Reference } from '../schema/reference';

export const REFERENCES: readonly Reference[] = [
  {
    id: referenceId('planck-2018-vi'),
    kind: 'journal-article',
    authors: 'Planck Collaboration',
    year: 2020,
    title: 'Planck 2018 results. VI. Cosmological parameters',
    source: 'Astronomy & Astrophysics 641, A6',
    doi: '10.1051/0004-6361/201833910',
    arxiv: '1807.06209',
    supports:
      'Base-ΛCDM parameters: age of the Universe, Hubble constant, matter and dark-energy densities.',
  },
  {
    id: referenceId('fixsen-2009-cmb-temperature'),
    kind: 'journal-article',
    authors: 'Fixsen, D. J.',
    year: 2009,
    title: 'The Temperature of the Cosmic Microwave Background',
    source: 'The Astrophysical Journal 707, 916',
    doi: '10.1088/0004-637X/707/2/916',
    arxiv: '0911.1955',
    supports: 'Present-day CMB monopole temperature.',
  },
  {
    id: referenceId('penzias-wilson-1965'),
    kind: 'journal-article',
    authors: 'Penzias, A. A. & Wilson, R. W.',
    year: 1965,
    title: 'A Measurement of Excess Antenna Temperature at 4080 Mc/s',
    source: 'The Astrophysical Journal 142, 419',
    doi: '10.1086/148307',
    supports: 'Discovery of the cosmic microwave background.',
  },
  {
    id: referenceId('hubble-1929'),
    kind: 'journal-article',
    authors: 'Hubble, E.',
    year: 1929,
    title: 'A Relation between Distance and Radial Velocity among Extra-Galactic Nebulae',
    source: 'Proceedings of the National Academy of Sciences 15, 168',
    doi: '10.1073/pnas.15.3.168',
    supports: 'The distance–redshift relation; first observational evidence for expansion.',
  },
  {
    id: referenceId('riess-1998'),
    kind: 'journal-article',
    authors: 'Riess, A. G. et al.',
    year: 1998,
    title:
      'Observational Evidence from Supernovae for an Accelerating Universe and a Cosmological Constant',
    source: 'The Astronomical Journal 116, 1009',
    doi: '10.1086/300499',
    arxiv: 'astro-ph/9805201',
    supports: 'Accelerating expansion from Type Ia supernovae.',
  },
  {
    id: referenceId('perlmutter-1999'),
    kind: 'journal-article',
    authors: 'Perlmutter, S. et al.',
    year: 1999,
    title: 'Measurements of Ω and Λ from 42 High-Redshift Supernovae',
    source: 'The Astrophysical Journal 517, 565',
    doi: '10.1086/307221',
    arxiv: 'astro-ph/9812133',
    supports: 'Independent supernova evidence for accelerating expansion.',
  },
  {
    id: referenceId('rubin-ford-1970'),
    kind: 'journal-article',
    authors: 'Rubin, V. C. & Ford, W. K.',
    year: 1970,
    title: 'Rotation of the Andromeda Nebula from a Spectroscopic Survey of Emission Regions',
    source: 'The Astrophysical Journal 159, 379',
    doi: '10.1086/150317',
    supports: 'Galaxy rotation curves that do not match the visible mass.',
  },
  {
    id: referenceId('einstein-1916-gr'),
    kind: 'journal-article',
    authors: 'Einstein, A.',
    year: 1916,
    title: 'Die Grundlage der allgemeinen Relativitätstheorie',
    source: 'Annalen der Physik 354, 769',
    doi: '10.1002/andp.19163540702',
    supports: 'The field equations of general relativity.',
  },
  {
    id: referenceId('newton-1687-principia'),
    kind: 'book',
    authors: 'Newton, I.',
    year: 1687,
    title: 'Philosophiæ Naturalis Principia Mathematica',
    source: 'Royal Society, London',
    supports: 'The three laws of motion and universal gravitation.',
  },
  {
    id: referenceId('ligo-2016-gw150914'),
    kind: 'journal-article',
    authors: 'Abbott, B. P. et al. (LIGO Scientific Collaboration and Virgo Collaboration)',
    year: 2016,
    title: 'Observation of Gravitational Waves from a Binary Black Hole Merger',
    source: 'Physical Review Letters 116, 061102',
    doi: '10.1103/PhysRevLett.116.061102',
    arxiv: '1602.03837',
    supports: 'First direct detection of gravitational waves; binary black hole merger.',
  },
  {
    id: referenceId('eht-2019-m87'),
    kind: 'journal-article',
    authors: 'Event Horizon Telescope Collaboration',
    year: 2019,
    title:
      'First M87 Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole',
    source: 'The Astrophysical Journal Letters 875, L1',
    doi: '10.3847/2041-8213/ab0ec7',
    supports: 'Horizon-scale image of the M87* black hole shadow.',
  },
  {
    id: referenceId('patterson-1956-age-of-earth'),
    kind: 'journal-article',
    authors: 'Patterson, C.',
    year: 1956,
    title: 'Age of meteorites and the earth',
    source: 'Geochimica et Cosmochimica Acta 10, 230',
    doi: '10.1016/0016-7037(56)90036-9',
    supports: 'Lead-isotope determination of the age of the Earth and meteorites.',
  },
  {
    id: referenceId('hublin-2017-jebel-irhoud'),
    kind: 'journal-article',
    authors: 'Hublin, J.-J. et al.',
    year: 2017,
    title: 'New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens',
    source: 'Nature 546, 289',
    doi: '10.1038/nature22336',
    supports: 'Earliest known Homo sapiens fossils and a pan-African origin model.',
  },
  {
    id: referenceId('codata-2018'),
    kind: 'review',
    authors: 'Tiesinga, E., Mohr, P. J., Newell, D. B. & Taylor, B. N.',
    year: 2021,
    title: 'CODATA recommended values of the fundamental physical constants: 2018',
    source: 'Reviews of Modern Physics 93, 025010',
    doi: '10.1103/RevModPhys.93.025010',
    supports: 'Values of the fundamental physical constants used throughout the platform.',
  },

  // ---- Added for Phase 1 (Cosmic Timeline) --------------------------------

  {
    id: referenceId('guth-1981-inflation'),
    kind: 'journal-article',
    authors: 'Guth, A. H.',
    year: 1981,
    title: 'Inflationary universe: A possible solution to the horizon and flatness problems',
    source: 'Physical Review D 23, 347',
    doi: '10.1103/PhysRevD.23.347',
    supports:
      'The original proposal of cosmic inflation and the problems it was designed to solve.',
  },
  {
    id: referenceId('alpher-bethe-gamow-1948'),
    kind: 'journal-article',
    authors: 'Alpher, R. A., Bethe, H. & Gamow, G.',
    year: 1948,
    title: 'The Origin of Chemical Elements',
    source: 'Physical Review 73, 803',
    doi: '10.1103/PhysRev.73.803',
    supports: 'The first quantitative treatment of element formation in a hot early Universe.',
  },
  {
    id: referenceId('cyburt-2016-bbn'),
    kind: 'review',
    authors: 'Cyburt, R. H., Fields, B. D., Olive, K. A. & Yeh, T.-H.',
    year: 2016,
    title: 'Big bang nucleosynthesis: Present status',
    source: 'Reviews of Modern Physics 88, 015004',
    doi: '10.1103/RevModPhys.88.015004',
    arxiv: '1505.01076',
    supports:
      'Predicted and observed primordial abundances of hydrogen, helium-4, deuterium and lithium-7, including the lithium problem.',
  },
  {
    id: referenceId('busza-2018-heavy-ion'),
    kind: 'review',
    authors: 'Busza, W., Rajagopal, K. & van der Schee, W.',
    year: 2018,
    title: 'Heavy Ion Collisions: The Big Picture and the Big Questions',
    source: 'Annual Review of Nuclear and Particle Science 68, 339',
    doi: '10.1146/annurev-nucl-101917-020852',
    arxiv: '1802.04801',
    supports:
      'Laboratory recreation of quark–gluon plasma, the state matter is thought to have been in during the first microseconds.',
  },
  {
    id: referenceId('b2fh-1957'),
    kind: 'journal-article',
    authors: 'Burbidge, E. M., Burbidge, G. R., Fowler, W. A. & Hoyle, F.',
    year: 1957,
    title: 'Synthesis of the Elements in Stars',
    source: 'Reviews of Modern Physics 29, 547',
    doi: '10.1103/RevModPhys.29.547',
    supports: 'The stellar origin of elements heavier than lithium.',
  },
  {
    id: referenceId('kenrick-crane-1997-land-plants'),
    kind: 'journal-article',
    authors: 'Kenrick, P. & Crane, P. R.',
    year: 1997,
    title: 'The origin and early evolution of plants on land',
    source: 'Nature 389, 33',
    doi: '10.1038/37918',
    supports: 'Fossil and phylogenetic evidence for the colonisation of land by plants.',
  },
  {
    id: referenceId('smoot-1992-cobe'),
    kind: 'journal-article',
    authors: 'Smoot, G. F. et al.',
    year: 1992,
    title: 'Structure in the COBE differential microwave radiometer first-year maps',
    source: 'The Astrophysical Journal 396, L1',
    doi: '10.1086/186504',
    supports: 'First detection of temperature anisotropies in the cosmic microwave background.',
  },
  {
    id: referenceId('bennett-2013-wmap9'),
    kind: 'journal-article',
    authors: 'Bennett, C. L. et al.',
    year: 2013,
    title:
      'Nine-Year Wilkinson Microwave Anisotropy Probe (WMAP) Observations: Final Maps and Results',
    source: 'The Astrophysical Journal Supplement Series 208, 20',
    doi: '10.1088/0067-0049/208/2/20',
    arxiv: '1212.5225',
    supports:
      'Independent CMB determination of cosmological parameters, including the epoch of recombination.',
  },
  {
    id: referenceId('bromm-larson-2004-first-stars'),
    kind: 'review',
    authors: 'Bromm, V. & Larson, R. B.',
    year: 2004,
    title: 'The First Stars',
    source: 'Annual Review of Astronomy and Astrophysics 42, 79',
    doi: '10.1146/annurev.astro.42.053102.134034',
    arxiv: 'astro-ph/0311019',
    supports: 'Theory of Population III star formation, expected masses and formation redshifts.',
  },
  {
    id: referenceId('stark-2016-first-billion-years'),
    kind: 'review',
    authors: 'Stark, D. P.',
    year: 2016,
    title: 'Galaxies in the First Billion Years After the Big Bang',
    source: 'Annual Review of Astronomy and Astrophysics 54, 761',
    doi: '10.1146/annurev-astro-081915-023417',
    supports: 'Observations of the earliest galaxies and the progress of cosmic reionization.',
  },
  {
    id: referenceId('curtis-lake-2023-jwst'),
    kind: 'journal-article',
    authors: 'Curtis-Lake, E. et al.',
    year: 2023,
    title: 'Spectroscopic confirmation of four metal-poor galaxies at z = 10.3–13.2',
    source: 'Nature Astronomy 7, 622',
    doi: '10.1038/s41550-023-01918-w',
    arxiv: '2212.04568',
    supports: 'JWST spectroscopic confirmation of galaxies within the first ~400 million years.',
  },
  {
    id: referenceId('springel-2005-millennium'),
    kind: 'journal-article',
    authors: 'Springel, V. et al.',
    year: 2005,
    title: 'Simulations of the formation, evolution and clustering of galaxies and quasars',
    source: 'Nature 435, 629',
    doi: '10.1038/nature03597',
    arxiv: 'astro-ph/0504097',
    supports:
      'Cosmological simulation reproducing the observed large-scale filamentary structure of galaxies.',
  },
  {
    id: referenceId('bouvier-wadhwa-2010-solar-system-age'),
    kind: 'journal-article',
    authors: 'Bouvier, A. & Wadhwa, M.',
    year: 2010,
    title:
      'The age of the Solar System redefined by the oldest Pb–Pb age of a meteoritic inclusion',
    source: 'Nature Geoscience 3, 637',
    doi: '10.1038/ngeo941',
    supports: 'Lead–lead age of a calcium–aluminium-rich inclusion: 4568.2 million years.',
  },
  {
    id: referenceId('canup-asphaug-2001-moon'),
    kind: 'journal-article',
    authors: 'Canup, R. M. & Asphaug, E.',
    year: 2001,
    title: "Origin of the Moon in a giant impact near the end of the Earth's formation",
    source: 'Nature 412, 708',
    doi: '10.1038/35089010',
    supports: 'The giant-impact model for the formation of the Moon.',
  },
  {
    id: referenceId('wilde-2001-jack-hills-zircons'),
    kind: 'journal-article',
    authors: 'Wilde, S. A., Valley, J. W., Peck, W. H. & Graham, C. M.',
    year: 2001,
    title:
      'Evidence from detrital zircons for the existence of continental crust and oceans on the Earth 4.4 Gyr ago',
    source: 'Nature 409, 175',
    doi: '10.1038/35051550',
    supports: 'Jack Hills zircons indicating liquid water and crust within ~150 Myr of formation.',
  },
  {
    id: referenceId('bell-2015-biogenic-carbon-zircon'),
    kind: 'journal-article',
    authors: 'Bell, E. A., Boehnke, P., Harrison, T. M. & Mao, W. L.',
    year: 2015,
    title: 'Potentially biogenic carbon preserved in a 4.1 billion-year-old zircon',
    source: 'Proceedings of the National Academy of Sciences 112, 14518',
    doi: '10.1073/pnas.1517557112',
    supports: 'Contested carbon-isotope evidence that has been interpreted as biogenic at 4.1 Ga.',
  },
  {
    id: referenceId('dodd-2017-hydrothermal-life'),
    kind: 'journal-article',
    authors: 'Dodd, M. S. et al.',
    year: 2017,
    title: "Evidence for early life in Earth's oldest hydrothermal vent precipitates",
    source: 'Nature 543, 60',
    doi: '10.1038/nature21377',
    supports: 'Claimed microfossils at 3.77–4.28 Ga; a disputed candidate for earliest life.',
  },
  {
    id: referenceId('lyons-2014-oxygen-rise'),
    kind: 'review',
    authors: 'Lyons, T. W., Reinhard, C. T. & Planavsky, N. J.',
    year: 2014,
    title: "The rise of oxygen in Earth's early ocean and atmosphere",
    source: 'Nature 506, 307',
    doi: '10.1038/nature13068',
    supports:
      'Reconstructed history of atmospheric oxygen, including the Great Oxidation Event and the Neoproterozoic rise.',
  },
  {
    id: referenceId('hoffman-1998-snowball-earth'),
    kind: 'journal-article',
    authors: 'Hoffman, P. F., Kaufman, A. J., Halverson, G. P. & Schrag, D. P.',
    year: 1998,
    title: 'A Neoproterozoic Snowball Earth',
    source: 'Science 281, 1342',
    doi: '10.1126/science.281.5381.1342',
    supports: 'The snowball-Earth hypothesis for global Neoproterozoic glaciation.',
  },
  {
    id: referenceId('knoll-2011-multicellularity'),
    kind: 'review',
    authors: 'Knoll, A. H.',
    year: 2011,
    title: 'The Multiple Origins of Complex Multicellularity',
    source: 'Annual Review of Earth and Planetary Sciences 39, 217',
    doi: '10.1146/annurev.earth.031208.100209',
    supports: 'Independent origins of complex multicellular life and their timing.',
  },
  {
    id: referenceId('erwin-2011-cambrian'),
    kind: 'journal-article',
    authors: 'Erwin, D. H. et al.',
    year: 2011,
    title:
      'The Cambrian conundrum: early divergence and later ecological success in the early history of animals',
    source: 'Science 334, 1091',
    doi: '10.1126/science.1206375',
    supports:
      'The mismatch between molecular divergence estimates and the fossil record of animal phyla.',
  },
  {
    id: referenceId('alvarez-1980-kpg'),
    kind: 'journal-article',
    authors: 'Alvarez, L. W., Alvarez, W., Asaro, F. & Michel, H. V.',
    year: 1980,
    title: 'Extraterrestrial Cause for the Cretaceous-Tertiary Extinction',
    source: 'Science 208, 1095',
    doi: '10.1126/science.208.4448.1095',
    supports: 'The iridium anomaly and the original impact hypothesis for the K-Pg extinction.',
  },
  {
    id: referenceId('schulte-2010-chicxulub'),
    kind: 'review',
    authors: 'Schulte, P. et al.',
    year: 2010,
    title: 'The Chicxulub Asteroid Impact and Mass Extinction at the Cretaceous-Paleogene Boundary',
    source: 'Science 327, 1214',
    doi: '10.1126/science.1177265',
    supports: 'Consensus review of the impact evidence and the timing of the extinction.',
  },
  {
    id: referenceId('brusatte-2015-dinosaur-extinction'),
    kind: 'review',
    authors: 'Brusatte, S. L. et al.',
    year: 2015,
    title: 'The extinction of the dinosaurs',
    source: 'Biological Reviews 90, 628',
    doi: '10.1111/brv.12128',
    supports:
      'State of the debate on dinosaur decline before the impact, and the survival of birds.',
  },
  {
    id: referenceId('oleary-2013-placental-mammals'),
    kind: 'journal-article',
    authors: "O'Leary, M. A. et al.",
    year: 2013,
    title: 'The Placental Mammal Ancestor and the Post–K-Pg Radiation of Placentals',
    source: 'Science 339, 662',
    doi: '10.1126/science.1229237',
    supports: 'Combined morphological and molecular reconstruction of the placental radiation.',
  },
  {
    id: referenceId('bloch-2007-primates'),
    kind: 'journal-article',
    authors: 'Bloch, J. I., Silcox, M. T., Boyer, D. M. & Sargis, E. J.',
    year: 2007,
    title:
      'New Paleocene skeletons and the relationship of plesiadapiforms to crown-clade primates',
    source: 'Proceedings of the National Academy of Sciences 104, 1159',
    doi: '10.1073/pnas.0610579104',
    supports: 'Early Paleocene fossils bearing on the origin of primates.',
  },
  {
    id: referenceId('brunet-2002-sahelanthropus'),
    kind: 'journal-article',
    authors: 'Brunet, M. et al.',
    year: 2002,
    title: 'A new hominid from the Upper Miocene of Chad, Central Africa',
    source: 'Nature 418, 145',
    doi: '10.1038/nature00879',
    supports: 'Sahelanthropus tchadensis at ~7 Ma, near the human–chimpanzee divergence.',
  },
  {
    id: referenceId('leakey-1995-australopithecus-anamensis'),
    kind: 'journal-article',
    authors: 'Leakey, M. G., Feibel, C. S., McDougall, I. & Walker, A.',
    year: 1995,
    title: 'New four-million-year-old hominid species from Kanapoi and Allia Bay, Kenya',
    source: 'Nature 376, 565',
    doi: '10.1038/376565a0',
    supports: 'Australopithecus anamensis and early evidence of hominin bipedality.',
  },
  {
    id: referenceId('villmoare-2015-early-homo'),
    kind: 'journal-article',
    authors: 'Villmoare, B. et al.',
    year: 2015,
    title: 'Early Homo at 2.8 Ma from Ledi-Geraru, Afar, Ethiopia',
    source: 'Science 347, 1352',
    doi: '10.1126/science.aaa1343',
    supports: 'The oldest well-dated fossil attributed to the genus Homo.',
  },
  {
    id: referenceId('bramble-lieberman-2004-endurance-running'),
    kind: 'journal-article',
    authors: 'Bramble, D. M. & Lieberman, D. E.',
    year: 2004,
    title: 'Endurance running and the evolution of Homo',
    source: 'Nature 432, 345',
    doi: '10.1038/nature03052',
    supports: 'Anatomical changes in Homo erectus associated with long-distance running.',
  },
  {
    id: referenceId('berger-2015-homo-naledi'),
    kind: 'journal-article',
    authors: 'Berger, L. R. et al.',
    year: 2015,
    title: 'Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa',
    source: 'eLife 4, e09560',
    doi: '10.7554/eLife.09560',
    supports:
      'A small-brained Homo species surviving alongside larger-brained ones; evidence that the hominin record is bushy.',
  },
  {
    id: referenceId('green-2010-neanderthal-genome'),
    kind: 'journal-article',
    authors: 'Green, R. E. et al.',
    year: 2010,
    title: 'A Draft Sequence of the Neandertal Genome',
    source: 'Science 328, 710',
    doi: '10.1126/science.1188021',
    supports: 'First evidence of Neanderthal ancestry in non-African modern human genomes.',
  },
  {
    id: referenceId('reich-2010-denisova'),
    kind: 'journal-article',
    authors: 'Reich, D. et al.',
    year: 2010,
    title: 'Genetic history of an archaic hominin group from Denisova Cave in Siberia',
    source: 'Nature 468, 1053',
    doi: '10.1038/nature09710',
    supports:
      'Identification of the Denisovans from DNA alone, and their ancestry in present-day Melanesians.',
  },
  {
    id: referenceId('prufer-2014-altai-neanderthal'),
    kind: 'journal-article',
    authors: 'Prüfer, K. et al.',
    year: 2014,
    title: 'The complete genome sequence of a Neanderthal from the Altai Mountains',
    source: 'Nature 505, 43',
    doi: '10.1038/nature12886',
    supports: 'High-coverage Neanderthal genome and quantified interbreeding with modern humans.',
  },
  {
    id: referenceId('vidal-2022-omo-kibish'),
    kind: 'journal-article',
    authors: 'Vidal, C. M. et al.',
    year: 2022,
    title: 'Age of the oldest known Homo sapiens from eastern Africa',
    source: 'Nature 601, 579',
    doi: '10.1038/s41586-021-04275-8',
    supports: 'Revised minimum age of ~233,000 years for the Omo Kibish Homo sapiens fossils.',
  },
  {
    id: referenceId('nielsen-2017-peopling-of-the-world'),
    kind: 'review',
    authors: 'Nielsen, R. et al.',
    year: 2017,
    title: 'Tracing the peopling of the world through genomics',
    source: 'Nature 541, 302',
    doi: '10.1038/nature21347',
    supports: 'Genomic evidence for the timing and routes of modern human dispersal.',
  },
  {
    id: referenceId('clarkson-2017-madjedbebe'),
    kind: 'journal-article',
    authors: 'Clarkson, C. et al.',
    year: 2017,
    title: 'Human occupation of northern Australia by 65,000 years ago',
    source: 'Nature 547, 306',
    doi: '10.1038/nature22968',
    supports: 'Archaeological dating of early modern human presence in Australia.',
  },
  {
    id: referenceId('zeder-2011-agriculture-origins'),
    kind: 'review',
    authors: 'Zeder, M. A.',
    year: 2011,
    title: 'The Origins of Agriculture in the Near East',
    source: 'Current Anthropology 52, S221',
    doi: '10.1086/659307',
    supports: 'Timing and process of plant and animal domestication in the Fertile Crescent.',
  },
  {
    id: referenceId('diamond-2002-domestication'),
    kind: 'journal-article',
    authors: 'Diamond, J.',
    year: 2002,
    title: 'Evolution, consequences and future of plant and animal domestication',
    source: 'Nature 418, 700',
    doi: '10.1038/nature01019',
    supports: 'Independent centres of domestication and their consequences.',
  },
  {
    id: referenceId('darwin-1859-origin'),
    kind: 'book',
    authors: 'Darwin, C.',
    year: 1859,
    title: 'On the Origin of Species by Means of Natural Selection',
    source: 'John Murray, London',
    supports: 'Descent with modification and branching common ancestry.',
  },
  {
    id: referenceId('riess-2022-sh0es'),
    kind: 'journal-article',
    authors: 'Riess, A. G. et al.',
    year: 2022,
    title:
      'A Comprehensive Measurement of the Local Value of the Hubble Constant with 1 km/s/Mpc Uncertainty from the Hubble Space Telescope and the SH0ES Team',
    source: 'The Astrophysical Journal Letters 934, L7',
    doi: '10.3847/2041-8213/ac5c5b',
    arxiv: '2112.04510',
    supports: 'Local distance-ladder value of H0 that is in tension with the CMB-derived value.',
  },
  {
    id: referenceId('ics-chart'),
    kind: 'agency-page',
    authors: 'International Commission on Stratigraphy',
    year: 2023,
    title: 'International Chronostratigraphic Chart',
    source: 'International Union of Geological Sciences',
    url: 'https://stratigraphy.org/chart',
    accessed: '2026-09-06',
    supports: 'Formal boundary ages for geological periods used throughout the timeline.',
  },

  // ---- Added for Phase 2 (Universe & Cosmology) ---------------------------

  {
    id: referenceId('lemaitre-1927'),
    kind: 'journal-article',
    authors: 'Lemaître, G.',
    year: 1927,
    title:
      'Un Univers homogène de masse constante et de rayon croissant rendant compte de la vitesse radiale des nébuleuses extra-galactiques',
    source: 'Annales de la Société Scientifique de Bruxelles A47, 49',
    url: 'https://ui.adsabs.harvard.edu/abs/1927ASSB...47...49L',
    accessed: '2026-09-06',
    supports:
      'The first derivation of an expanding-universe solution together with a linear velocity–distance relation.',
  },
  {
    id: referenceId('friedmann-1922'),
    kind: 'journal-article',
    authors: 'Friedmann, A.',
    year: 1922,
    title: 'Über die Krümmung des Raumes',
    source: 'Zeitschrift für Physik 10, 377',
    doi: '10.1007/BF01332580',
    supports: 'The dynamical equations governing an expanding homogeneous universe.',
  },
  {
    id: referenceId('linde-1982-new-inflation'),
    kind: 'journal-article',
    authors: 'Linde, A. D.',
    year: 1982,
    title:
      'A new inflationary universe scenario: A possible solution of the horizon, flatness, homogeneity, isotropy and primordial monopole problems',
    source: 'Physics Letters B 108, 389',
    doi: '10.1016/0370-2693(82)91219-9',
    supports: 'The slow-roll formulation of inflation that made the framework workable.',
  },
  {
    id: referenceId('bicep-keck-2021'),
    kind: 'journal-article',
    authors: 'BICEP/Keck Collaboration (Ade, P. A. R. et al.)',
    year: 2021,
    title:
      'Improved Constraints on Primordial Gravitational Waves using Planck, WMAP, and BICEP/Keck Observations through the 2018 Observing Season',
    source: 'Physical Review Letters 127, 151301',
    doi: '10.1103/PhysRevLett.127.151301',
    arxiv: '2110.00483',
    supports:
      'The current upper limit on the tensor-to-scalar ratio, r < 0.036 — inflation’s signature prediction remains undetected.',
  },
  {
    id: referenceId('ijjas-steinhardt-loeb-2013'),
    kind: 'journal-article',
    authors: 'Ijjas, A., Steinhardt, P. J. & Loeb, A.',
    year: 2013,
    title: 'Inflationary paradigm in trouble after Planck2013',
    source: 'Physics Letters B 723, 261',
    doi: '10.1016/j.physletb.2013.05.023',
    arxiv: '1304.2785',
    supports:
      'A critique of inflation from within the field: the framework’s flexibility weakens its predictive power.',
  },
  {
    id: referenceId('mather-1994-cobe-firas'),
    kind: 'journal-article',
    authors: 'Mather, J. C. et al.',
    year: 1994,
    title: 'Measurement of the cosmic microwave background spectrum by the COBE FIRAS instrument',
    source: 'The Astrophysical Journal 420, 439',
    doi: '10.1086/173574',
    supports:
      'The CMB is a blackbody to within 50 parts per million — the most precise blackbody spectrum ever measured.',
  },
  {
    id: referenceId('gamow-1948'),
    kind: 'journal-article',
    authors: 'Gamow, G.',
    year: 1948,
    title: 'The Evolution of the Universe',
    source: 'Nature 162, 680',
    doi: '10.1038/162680a0',
    supports: 'The prediction that a hot early universe would leave behind relic radiation.',
  },
  {
    id: referenceId('zwicky-1933'),
    kind: 'journal-article',
    authors: 'Zwicky, F.',
    year: 1933,
    title: 'Die Rotverschiebung von extragalaktischen Nebeln',
    source: 'Helvetica Physica Acta 6, 110',
    url: 'https://ui.adsabs.harvard.edu/abs/1933AcHPh...6..110Z',
    accessed: '2026-09-06',
    supports:
      'The first evidence for missing mass: galaxy velocities in the Coma cluster far exceed what its visible matter can bind.',
  },
  {
    id: referenceId('clowe-2006-bullet-cluster'),
    kind: 'journal-article',
    authors: 'Clowe, D. et al.',
    year: 2006,
    title: 'A Direct Empirical Proof of the Existence of Dark Matter',
    source: 'The Astrophysical Journal Letters 648, L109',
    doi: '10.1086/508162',
    arxiv: 'astro-ph/0608407',
    supports:
      'In the Bullet Cluster the lensing mass is separated from the hot gas, which is hard to explain by modifying gravity alone.',
  },
  {
    id: referenceId('lux-zeplin-2023'),
    kind: 'journal-article',
    authors: 'LZ Collaboration (Aalbers, J. et al.)',
    year: 2023,
    title: 'First Dark Matter Search Results from the LUX-ZEPLIN (LZ) Experiment',
    source: 'Physical Review Letters 131, 041002',
    doi: '10.1103/PhysRevLett.131.041002',
    arxiv: '2207.03764',
    supports:
      'A leading direct-detection search returning null results: no dark-matter particle has been detected.',
  },
  {
    id: referenceId('bertone-hooper-2018-history'),
    kind: 'review',
    authors: 'Bertone, G. & Hooper, D.',
    year: 2018,
    title: 'History of dark matter',
    source: 'Reviews of Modern Physics 90, 045002',
    doi: '10.1103/RevModPhys.90.045002',
    arxiv: '1605.04909',
    supports: 'A review of the evidence for dark matter and of the candidates proposed for it.',
  },
  {
    id: referenceId('weinberg-1989-cc-problem'),
    kind: 'review',
    authors: 'Weinberg, S.',
    year: 1989,
    title: 'The cosmological constant problem',
    source: 'Reviews of Modern Physics 61, 1',
    doi: '10.1103/RevModPhys.61.1',
    supports:
      'The mismatch between the observed vacuum energy density and quantum field theory estimates.',
  },
  {
    id: referenceId('brout-2022-pantheon-plus'),
    kind: 'journal-article',
    authors: 'Brout, D. et al.',
    year: 2022,
    title: 'The Pantheon+ Analysis: Cosmological Constraints',
    source: 'The Astrophysical Journal 938, 110',
    doi: '10.3847/1538-4357/ac8e04',
    arxiv: '2202.04077',
    supports:
      'A compilation of 1550 Type Ia supernovae constraining the expansion history and the dark-energy equation of state.',
  },
  {
    id: referenceId('eisenstein-2005-bao'),
    kind: 'journal-article',
    authors: 'Eisenstein, D. J. et al.',
    year: 2005,
    title:
      'Detection of the Baryon Acoustic Peak in the Large-Scale Correlation Function of SDSS Luminous Red Galaxies',
    source: 'The Astrophysical Journal 633, 560',
    doi: '10.1086/466512',
    arxiv: 'astro-ph/0501171',
    supports:
      'Baryon acoustic oscillations detected in the galaxy distribution — a standard ruler independent of supernovae.',
  },
  {
    id: referenceId('desi-2024-bao'),
    kind: 'journal-article',
    authors: 'DESI Collaboration (Adame, A. G. et al.)',
    year: 2025,
    title:
      'DESI 2024 VI: cosmological constraints from the measurements of baryon acoustic oscillations',
    source: 'Journal of Cosmology and Astroparticle Physics 2025(02), 021',
    doi: '10.1088/1475-7516/2025/02/021',
    arxiv: '2404.03002',
    supports:
      'Baryon acoustic oscillation measurements that, combined with other data, hint at dark energy possibly evolving with time.',
  },
  {
    id: referenceId('gott-2005-map-of-the-universe'),
    kind: 'journal-article',
    authors: 'Gott, J. R. et al.',
    year: 2005,
    title: 'A Map of the Universe',
    source: 'The Astrophysical Journal 624, 463',
    doi: '10.1086/428890',
    arxiv: 'astro-ph/0310571',
    supports:
      'Comoving distance to the particle horizon: the observable Universe is about 46 billion light-years in radius.',
  },
  {
    id: referenceId('geller-huchra-1989'),
    kind: 'journal-article',
    authors: 'Geller, M. J. & Huchra, J. P.',
    year: 1989,
    title: 'Mapping the Universe',
    source: 'Science 246, 897',
    doi: '10.1126/science.246.4932.897',
    supports:
      'The first redshift surveys revealing that galaxies lie on sheets and filaments surrounding vast voids.',
  },
  {
    id: referenceId('vogelsberger-2014-illustris'),
    kind: 'journal-article',
    authors: 'Vogelsberger, M. et al.',
    year: 2014,
    title: 'Properties of galaxies reproduced by a hydrodynamic simulation',
    source: 'Nature 509, 177',
    doi: '10.1038/nature13316',
    arxiv: '1405.1418',
    supports:
      'Cosmological simulations reproduce observed large-scale structure and galaxy populations under ΛCDM.',
  },
  {
    id: referenceId('planck-2018-x-inflation'),
    kind: 'journal-article',
    authors: 'Planck Collaboration',
    year: 2020,
    title: 'Planck 2018 results. X. Constraints on inflation',
    source: 'Astronomy & Astrophysics 641, A10',
    doi: '10.1051/0004-6361/201833887',
    arxiv: '1807.06211',
    supports:
      'Measured scalar spectral index and limits on primordial gravitational waves and non-Gaussianity.',
  },
  {
    id: referenceId('pdg-2024'),
    kind: 'review',
    authors: 'Particle Data Group (Navas, S. et al.)',
    year: 2024,
    title: 'Review of Particle Physics',
    source: 'Physical Review D 110, 030001',
    doi: '10.1103/PhysRevD.110.030001',
    supports:
      'Reference values for particle properties and for the cosmological parameters reviewed by the PDG.',
  },
  {
    id: referenceId('freedman-2021-h0'),
    kind: 'journal-article',
    authors: 'Freedman, W. L.',
    year: 2021,
    title: 'Measurements of the Hubble Constant: Tensions in Perspective',
    source: 'The Astrophysical Journal 919, 16',
    doi: '10.3847/1538-4357/ac0e95',
    arxiv: '2106.15656',
    supports:
      'An independent distance-ladder calibration giving a value between the CMB and SH0ES results.',
  },

  // ---- Added for Phase 3 (Gravity & Newton) -------------------------------

  {
    id: referenceId('galileo-1638-two-new-sciences'),
    kind: 'book',
    authors: 'Galilei, G.',
    year: 1638,
    title: 'Discorsi e Dimostrazioni Matematiche intorno a due nuove scienze',
    source: 'Elzevir, Leiden',
    supports:
      'The argument and inclined-plane experiments showing that bodies of different weight fall with the same acceleration when resistance is removed, and that fall is uniformly accelerated.',
  },
  {
    id: referenceId('kepler-1609-astronomia-nova'),
    kind: 'book',
    authors: 'Kepler, J.',
    year: 1609,
    title: 'Astronomia Nova',
    source: 'Heidelberg',
    supports:
      'The elliptical orbit of Mars and the equal-areas law — the empirical regularities Newton later derived from the inverse-square law.',
  },
  {
    id: referenceId('cavendish-1798'),
    kind: 'journal-article',
    authors: 'Cavendish, H.',
    year: 1798,
    title: 'Experiments to Determine the Density of the Earth',
    source: 'Philosophical Transactions of the Royal Society of London 88, 469',
    doi: '10.1098/rstl.1798.0022',
    supports:
      'The torsion-balance measurement of the gravitational attraction between laboratory masses, from which G and the mass of the Earth follow.',
  },
  {
    id: referenceId('nasa-planetary-factsheet'),
    kind: 'agency-page',
    authors: 'Williams, D. R. (NASA Goddard Space Flight Center)',
    year: 2024,
    title: 'Planetary Fact Sheet',
    source: 'NASA Space Science Data Coordinated Archive',
    url: 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/',
    accessed: '2026-09-06',
    supports:
      'Masses, radii, surface gravities, escape velocities and orbital parameters for the Sun, planets and Moon.',
  },
  {
    id: referenceId('iau-2015-nominal-constants'),
    kind: 'journal-article',
    authors: 'Mamajek, E. E. et al.',
    year: 2015,
    title:
      'IAU 2015 Resolution B3 on Recommended Nominal Conversion Constants for Selected Solar and Planetary Properties',
    source: 'Proceedings of the IAU / arXiv',
    arxiv: '1510.07674',
    supports:
      'Nominal values of the solar and terrestrial gravitational parameters GM, which are known far more precisely than either G or the masses separately.',
  },
  {
    id: referenceId('nasa-apollo15-feather-drop'),
    kind: 'agency-page',
    authors: 'NASA (Apollo 15 crew; Scott, D. R.)',
    year: 1971,
    title: 'Apollo 15 Hammer and Feather Drop',
    source: 'NASA Space Science Data Coordinated Archive',
    url: 'https://nssdc.gsfc.nasa.gov/planetary/lunar/apollo_15_feather_drop.html',
    accessed: '2026-09-06',
    supports:
      'A hammer and a falcon feather released together on the Moon reaching the surface together, in a vacuum, on film.',
  },
  {
    id: referenceId('touboul-2022-microscope'),
    kind: 'journal-article',
    authors: 'Touboul, P. et al. (MICROSCOPE Collaboration)',
    year: 2022,
    title: 'MICROSCOPE Mission: Final Results of the Test of the Equivalence Principle',
    source: 'Physical Review Letters 129, 121102',
    doi: '10.1103/PhysRevLett.129.121102',
    supports:
      'The most precise test of the universality of free fall: two test masses of different composition fall alike to better than one part in 10^15.',
  },
  {
    id: referenceId('williams-2012-lunar-laser'),
    kind: 'journal-article',
    authors: 'Williams, J. G., Turyshev, S. G. & Boggs, D. H.',
    year: 2012,
    title: 'Lunar laser ranging tests of the equivalence principle',
    source: 'Classical and Quantum Gravity 29, 184004',
    doi: '10.1088/0264-9381/29/18/184004',
    arxiv: '1203.2150',
    supports:
      'Centimetre-level ranging to retroreflectors on the Moon, testing the equivalence principle for massive bodies and constraining departures from Newtonian gravity.',
  },
  {
    id: referenceId('park-2017-mercury-precession'),
    kind: 'journal-article',
    authors: 'Park, R. S. et al.',
    year: 2017,
    title: "Precession of Mercury's Perihelion from Ranging to the MESSENGER Spacecraft",
    source: 'The Astronomical Journal 153, 121',
    doi: '10.3847/1538-3881/aa5be2',
    supports:
      "The measured excess precession of Mercury's perihelion, 42.9799 ± 0.0009 arcseconds per century, matching general relativity.",
  },
  {
    id: referenceId('will-2014-confrontation'),
    kind: 'review',
    authors: 'Will, C. M.',
    year: 2014,
    title: 'The Confrontation between General Relativity and Experiment',
    source: 'Living Reviews in Relativity 17, 4',
    doi: '10.12942/lrr-2014-4',
    arxiv: '1403.7377',
    supports:
      'A systematic review of where Newtonian gravity is sufficient, the size of the leading relativistic corrections, and the experiments that measure them.',
  },
  {
    id: referenceId('dyson-1920-eclipse'),
    kind: 'journal-article',
    authors: 'Dyson, F. W., Eddington, A. S. & Davidson, C.',
    year: 1920,
    title:
      "A Determination of the Deflection of Light by the Sun's Gravitational Field, from Observations Made at the Total Eclipse of May 29, 1919",
    source: 'Philosophical Transactions of the Royal Society A 220, 291',
    doi: '10.1098/rsta.1920.0009',
    supports:
      'The eclipse measurement of starlight deflection, roughly twice the value a Newtonian corpuscular calculation gives.',
  },
  {
    id: referenceId('pound-rebka-1960'),
    kind: 'journal-article',
    authors: 'Pound, R. V. & Rebka, G. A.',
    year: 1960,
    title: 'Apparent Weight of Photons',
    source: 'Physical Review Letters 4, 337',
    doi: '10.1103/PhysRevLett.4.337',
    supports:
      'The first laboratory measurement of gravitational frequency shift, over a 22.5 m tower.',
  },
  {
    id: referenceId('chou-2010-optical-clocks'),
    kind: 'journal-article',
    authors: 'Chou, C. W., Hume, D. B., Rosenband, T. & Wineland, D. J.',
    year: 2010,
    title: 'Optical Clocks and Relativity',
    source: 'Science 329, 1630',
    doi: '10.1126/science.1192720',
    supports:
      'Gravitational time dilation measured over a height difference of 33 centimetres in a single laboratory.',
  },
  {
    id: referenceId('ashby-2003-gps'),
    kind: 'review',
    authors: 'Ashby, N.',
    year: 2003,
    title: 'Relativity in the Global Positioning System',
    source: 'Living Reviews in Relativity 6, 1',
    doi: '10.12942/lrr-2003-1',
    supports:
      'The size of the relativistic clock corrections GPS must apply, and what the system would do without them.',
  },
  {
    id: referenceId('agnew-2015-earth-tides'),
    kind: 'review',
    authors: 'Agnew, D. C.',
    year: 2015,
    title: 'Earth Tides',
    source: 'Treatise on Geophysics, 2nd edition, Volume 3, 151–178',
    doi: '10.1016/B978-0-444-53802-4.00058-0',
    supports:
      'The tidal potential and the differential-acceleration origin of the two bulges; the relative size of the lunar and solar tidal forcing.',
  },
  {
    id: referenceId('noaa-tides-tutorial'),
    kind: 'agency-page',
    authors: 'NOAA National Ocean Service',
    year: 2024,
    title: 'Tides and Water Levels: What Causes Tides?',
    source: 'NOAA Ocean Service Education',
    url: 'https://oceanservice.noaa.gov/education/tutorial_tides/',
    accessed: '2026-09-06',
    supports:
      'Spring and neap tides, tidal ranges, and why observed tides at a coast depend heavily on local basin shape.',
  },
  {
    id: referenceId('vallado-2013-astrodynamics'),
    kind: 'book',
    authors: 'Vallado, D. A.',
    year: 2013,
    title: 'Fundamentals of Astrodynamics and Applications, 4th edition',
    source: 'Microcosm Press / Springer',
    supports:
      'The two-body problem, orbital energy and the vis-viva equation, conic-section trajectories, and escape conditions.',
  },
  {
    id: referenceId('cgpm-1901-standard-gravity'),
    kind: 'agency-page',
    authors: 'General Conference on Weights and Measures (CGPM), 3rd meeting',
    year: 1901,
    title: 'Declaration on the unit of mass and on the definition of standard gravity',
    source: 'Bureau International des Poids et Mesures (BIPM)',
    url: 'https://www.bipm.org/en/committees/cg/cgpm/3-1901/resolution-2',
    accessed: '2026-09-06',
    supports:
      'The conventional value of standard gravity, 9.80665 m/s², adopted by definition rather than measured.',
  },

  // ---- Added for Phase 4 (Einstein & Relativity) --------------------------

  {
    id: referenceId('einstein-1905-sr'),
    kind: 'journal-article',
    authors: 'Einstein, A.',
    year: 1905,
    title: 'Zur Elektrodynamik bewegter Körper',
    source: 'Annalen der Physik 322, 891',
    doi: '10.1002/andp.19053221004',
    supports:
      'The two postulates of special relativity, the relativity of simultaneity, time dilation and length contraction.',
  },
  {
    id: referenceId('einstein-1905-inertia'),
    kind: 'journal-article',
    authors: 'Einstein, A.',
    year: 1905,
    title: 'Ist die Trägheit eines Körpers von seinem Energieinhalt abhängig?',
    source: 'Annalen der Physik 323, 639',
    doi: '10.1002/andp.19053231314',
    supports: 'The equivalence of mass and energy, later written E = mc².',
  },
  {
    id: referenceId('michelson-morley-1887'),
    kind: 'journal-article',
    authors: 'Michelson, A. A. & Morley, E. W.',
    year: 1887,
    title: 'On the Relative Motion of the Earth and the Luminiferous Ether',
    source: 'American Journal of Science s3-34, 333',
    doi: '10.2475/ajs.s3-34.203.333',
    supports:
      'The null result for motion of the Earth through a light-carrying medium, at a sensitivity far above the expected effect.',
  },
  {
    id: referenceId('minkowski-1952-space-and-time'),
    kind: 'book',
    authors: 'Minkowski, H.',
    year: 1952,
    title: 'Space and Time (1908 address), in The Principle of Relativity',
    source: 'Dover Publications, New York',
    supports:
      'The unification of space and time into one four-dimensional geometry, and the invariant spacetime interval.',
  },
  {
    id: referenceId('schwarzschild-1916'),
    kind: 'journal-article',
    authors: 'Schwarzschild, K.',
    year: 1916,
    title: 'Über das Gravitationsfeld eines Massenpunktes nach der Einsteinschen Theorie',
    source:
      'Sitzungsberichte der Königlich Preussischen Akademie der Wissenschaften, 189 (English translation, arXiv)',
    arxiv: 'physics/9905030',
    supports:
      'The first exact solution of the Einstein field equations, and the radius that now bears his name.',
  },
  {
    id: referenceId('frisch-smith-1963-muons'),
    kind: 'journal-article',
    authors: 'Frisch, D. H. & Smith, J. H.',
    year: 1963,
    title: 'Measurement of the Relativistic Time Dilation Using μ-Mesons',
    source: 'American Journal of Physics 31, 342',
    doi: '10.1119/1.1969508',
    supports:
      'Cosmic-ray muons surviving the trip from a mountain top to sea level in numbers that only time dilation explains.',
  },
  {
    id: referenceId('bailey-1977-muon-lifetime'),
    kind: 'journal-article',
    authors: 'Bailey, J. et al.',
    year: 1977,
    title:
      'Measurements of relativistic time dilatation for positive and negative muons in a circular orbit',
    source: 'Nature 268, 301',
    doi: '10.1038/268301a0',
    supports:
      'Muon lifetime dilated by a factor of 29.3 in a storage ring, agreeing with special relativity to 2 parts in 1000.',
  },
  {
    id: referenceId('hafele-keating-1972'),
    kind: 'journal-article',
    authors: 'Hafele, J. C. & Keating, R. E.',
    year: 1972,
    title: 'Around-the-World Atomic Clocks: Observed Relativistic Time Gains',
    source: 'Science 177, 168',
    doi: '10.1126/science.177.4044.168',
    supports:
      'Caesium clocks flown around the world disagreeing with clocks left behind, by the predicted number of nanoseconds.',
  },
  {
    id: referenceId('delva-2018-galileo-redshift'),
    kind: 'journal-article',
    authors: 'Delva, P. et al.',
    year: 2018,
    title: 'Gravitational Redshift Test Using Eccentric Galileo Satellites',
    source: 'Physical Review Letters 121, 231101',
    doi: '10.1103/PhysRevLett.121.231101',
    supports:
      'The gravitational redshift confirmed to about 2 parts in 100,000 using two satellites accidentally launched into eccentric orbits.',
  },
  {
    id: referenceId('bertotti-2003-cassini'),
    kind: 'journal-article',
    authors: 'Bertotti, B., Iess, L. & Tortora, P.',
    year: 2003,
    title: 'A test of general relativity using radio links with the Cassini spacecraft',
    source: 'Nature 425, 374',
    doi: '10.1038/nature01997',
    supports:
      'The Shapiro delay of radio signals passing the Sun, constraining the PPN parameter γ to 1 within 2.3 × 10⁻⁵.',
  },
  {
    id: referenceId('everitt-2011-gravity-probe-b'),
    kind: 'journal-article',
    authors: 'Everitt, C. W. F. et al.',
    year: 2011,
    title: 'Gravity Probe B: Final Results of a Space Experiment to Test General Relativity',
    source: 'Physical Review Letters 106, 221101',
    doi: '10.1103/PhysRevLett.106.221101',
    supports:
      'Direct measurement of the geodetic effect and of frame dragging by the rotating Earth.',
  },
  {
    id: referenceId('walsh-1979-twin-quasar'),
    kind: 'journal-article',
    authors: 'Walsh, D., Carswell, R. F. & Weymann, R. J.',
    year: 1979,
    title: '0957+561 A, B: twin quasistellar objects or gravitational lens?',
    source: 'Nature 279, 381',
    doi: '10.1038/279381a0',
    supports: 'The first identified gravitational lens: one quasar seen twice.',
  },
  {
    id: referenceId('hulse-taylor-1975'),
    kind: 'journal-article',
    authors: 'Hulse, R. A. & Taylor, J. H.',
    year: 1975,
    title: 'Discovery of a pulsar in a binary system',
    source: 'The Astrophysical Journal 195, L51',
    doi: '10.1086/181708',
    supports:
      'The binary pulsar PSR B1913+16, the first system to show orbital decay by gravitational radiation.',
  },
  {
    id: referenceId('weisberg-huang-2016-binary-pulsar'),
    kind: 'journal-article',
    authors: 'Weisberg, J. M. & Huang, Y.',
    year: 2016,
    title: 'Relativistic Measurements from Timing the Binary Pulsar PSR B1913+16',
    source: 'The Astrophysical Journal 829, 55',
    doi: '10.3847/0004-637X/829/1/55',
    arxiv: '1606.02744',
    supports:
      'Forty years of orbital decay matching the general-relativistic prediction to about 0.2%.',
  },
  {
    id: referenceId('abbott-2017-gw170817'),
    kind: 'journal-article',
    authors: 'Abbott, B. P. et al. (LIGO Scientific Collaboration and Virgo Collaboration)',
    year: 2017,
    title: 'GW170817: Observation of Gravitational Waves from a Binary Neutron Star Inspiral',
    source: 'Physical Review Letters 119, 161101',
    doi: '10.1103/PhysRevLett.119.161101',
    supports:
      'Gravitational waves and light from the same event, constraining the speed of gravity to that of light.',
  },
  {
    id: referenceId('abbott-2023-gwtc3'),
    kind: 'journal-article',
    authors: 'Abbott, R. et al. (LIGO–Virgo–KAGRA Collaboration)',
    year: 2023,
    title:
      'GWTC-3: Compact Binary Coalescences Observed by LIGO and Virgo during the Second Part of the Third Observing Run',
    source: 'Physical Review X 13, 041039',
    doi: '10.1103/PhysRevX.13.041039',
    arxiv: '2111.03606',
    supports: 'The catalogue of gravitational-wave detections through the third observing run.',
  },
  {
    id: referenceId('gravity-2018-s2-redshift'),
    kind: 'journal-article',
    authors: 'GRAVITY Collaboration',
    year: 2018,
    title:
      'Detection of the gravitational redshift in the orbit of the star S2 near the Galactic centre massive black hole',
    source: 'Astronomy & Astrophysics 615, L15',
    doi: '10.1051/0004-6361/201833718',
    supports:
      'Gravitational redshift measured in the orbit of a star passing close to the Milky Way’s central black hole.',
  },
  {
    id: referenceId('eht-2022-sgr-a'),
    kind: 'journal-article',
    authors: 'Event Horizon Telescope Collaboration',
    year: 2022,
    title:
      'First Sagittarius A* Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole in the Center of the Milky Way',
    source: 'The Astrophysical Journal Letters 930, L12',
    doi: '10.3847/2041-8213/ac6674',
    supports:
      'Horizon-scale imaging of the black hole at the centre of our own galaxy, with a shadow of the size general relativity predicts.',
  },
  {
    id: referenceId('taylor-wheeler-1992-spacetime'),
    kind: 'book',
    authors: 'Taylor, E. F. & Wheeler, J. A.',
    year: 1992,
    title: 'Spacetime Physics: Introduction to Special Relativity, 2nd edition',
    source: 'W. H. Freeman, New York',
    supports:
      'The spacetime interval, light cones, proper time, and the standard worked treatments of the twin and pole–barn problems.',
  },
  {
    id: referenceId('hartle-2003-gravity'),
    kind: 'book',
    authors: 'Hartle, J. B.',
    year: 2003,
    title: 'Gravity: An Introduction to Einstein’s General Relativity',
    source: 'Addison-Wesley, San Francisco',
    supports:
      'Geodesics, the Schwarzschild solution, gravitational redshift, light deflection and perihelion precession.',
  },
  {
    id: referenceId('misner-thorne-wheeler-1973'),
    kind: 'book',
    authors: 'Misner, C. W., Thorne, K. S. & Wheeler, J. A.',
    year: 1973,
    title: 'Gravitation',
    source: 'W. H. Freeman, San Francisco',
    supports:
      'The field equations, tidal curvature, and the standard reference treatment of general relativity.',
  },

  // --- Black holes -------------------------------------------------------
  {
    id: referenceId('oppenheimer-snyder-1939'),
    kind: 'journal-article',
    authors: 'Oppenheimer, J. R. & Snyder, H.',
    year: 1939,
    title: 'On Continued Gravitational Contraction',
    source: 'Physical Review 56, 455',
    doi: '10.1103/PhysRev.56.455',
    supports:
      'First general-relativistic treatment of the collapse of a massive star through its own gravitational radius.',
  },
  {
    id: referenceId('oppenheimer-volkoff-1939'),
    kind: 'journal-article',
    authors: 'Oppenheimer, J. R. & Volkoff, G. M.',
    year: 1939,
    title: 'On Massive Neutron Cores',
    source: 'Physical Review 55, 374',
    doi: '10.1103/PhysRev.55.374',
    supports:
      'The existence of a maximum mass for a neutron star supported by degeneracy pressure.',
  },
  {
    id: referenceId('chandrasekhar-1931'),
    kind: 'journal-article',
    authors: 'Chandrasekhar, S.',
    year: 1931,
    title: 'The Maximum Mass of Ideal White Dwarfs',
    source: 'The Astrophysical Journal 74, 81',
    doi: '10.1086/143324',
    supports:
      'The white-dwarf mass limit above which electron degeneracy pressure cannot support a core.',
  },
  {
    id: referenceId('kerr-1963'),
    kind: 'journal-article',
    authors: 'Kerr, R. P.',
    year: 1963,
    title: 'Gravitational Field of a Spinning Mass as an Example of Algebraically Special Metrics',
    source: 'Physical Review Letters 11, 237',
    doi: '10.1103/PhysRevLett.11.237',
    supports:
      'The exact solution for a rotating black hole, including the ergosphere and frame dragging.',
  },
  {
    id: referenceId('penrose-1965-singularities'),
    kind: 'journal-article',
    authors: 'Penrose, R.',
    year: 1965,
    title: 'Gravitational Collapse and Space-Time Singularities',
    source: 'Physical Review Letters 14, 57',
    doi: '10.1103/PhysRevLett.14.57',
    supports:
      'The singularity theorem: singularity formation in gravitational collapse is generic, not an artefact of assumed symmetry.',
  },
  {
    id: referenceId('bekenstein-1973-entropy'),
    kind: 'journal-article',
    authors: 'Bekenstein, J. D.',
    year: 1973,
    title: 'Black Holes and Entropy',
    source: 'Physical Review D 7, 2333',
    doi: '10.1103/PhysRevD.7.2333',
    supports: 'Black-hole entropy proportional to horizon area.',
  },
  {
    id: referenceId('hawking-1975-radiation'),
    kind: 'journal-article',
    authors: 'Hawking, S. W.',
    year: 1975,
    title: 'Particle Creation by Black Holes',
    source: 'Communications in Mathematical Physics 43, 199',
    doi: '10.1007/BF02345020',
    supports:
      'The prediction that black holes radiate thermally, with a temperature inversely proportional to mass.',
  },
  {
    id: referenceId('hawking-1976-information'),
    kind: 'journal-article',
    authors: 'Hawking, S. W.',
    year: 1976,
    title: 'Breakdown of Predictability in Gravitational Collapse',
    source: 'Physical Review D 14, 2460',
    doi: '10.1103/PhysRevD.14.2460',
    supports: 'The original statement of the black-hole information problem.',
  },
  {
    id: referenceId('bardeen-carter-hawking-1973'),
    kind: 'journal-article',
    authors: 'Bardeen, J. M., Carter, B. & Hawking, S. W.',
    year: 1973,
    title: 'The Four Laws of Black Hole Mechanics',
    source: 'Communications in Mathematical Physics 31, 161',
    doi: '10.1007/BF01645742',
    supports: 'The formal analogy between black-hole mechanics and the laws of thermodynamics.',
  },
  {
    id: referenceId('shakura-sunyaev-1973'),
    kind: 'journal-article',
    authors: 'Shakura, N. I. & Sunyaev, R. A.',
    year: 1973,
    title: 'Black Holes in Binary Systems. Observational Appearance',
    source: 'Astronomy & Astrophysics 24, 337',
    url: 'https://ui.adsabs.harvard.edu/abs/1973A&A....24..337S',
    accessed: '2026-09-07',
    supports:
      'The standard thin accretion-disc model and the efficiency of converting rest mass into radiation.',
  },
  {
    id: referenceId('blandford-znajek-1977'),
    kind: 'journal-article',
    authors: 'Blandford, R. D. & Znajek, R. L.',
    year: 1977,
    title: 'Electromagnetic extraction of energy from Kerr black holes',
    source: 'Monthly Notices of the Royal Astronomical Society 179, 433',
    doi: '10.1093/mnras/179.3.433',
    supports:
      'A mechanism for powering relativistic jets from the rotational energy of a black hole.',
  },
  {
    id: referenceId('remillard-mcclintock-2006'),
    kind: 'review',
    authors: 'Remillard, R. A. & McClintock, J. E.',
    year: 2006,
    title: 'X-ray Properties of Black-Hole Binaries',
    source: 'Annual Review of Astronomy and Astrophysics 44, 49',
    doi: '10.1146/annurev.astro.44.051905.092532',
    arxiv: '0606352',
    supports:
      'Dynamical mass measurements and X-ray behaviour of stellar-mass black holes in binaries.',
  },
  {
    id: referenceId('ghez-2008-galactic-centre'),
    kind: 'journal-article',
    authors: 'Ghez, A. M. et al.',
    year: 2008,
    title:
      'Measuring Distance and Properties of the Milky Way’s Central Supermassive Black Hole with Stellar Orbits',
    source: 'The Astrophysical Journal 689, 1044',
    doi: '10.1086/592738',
    arxiv: '0808.2870',
    supports:
      'Stellar orbits at the Galactic centre constraining the mass and compactness of Sgr A*.',
  },
  {
    id: referenceId('gravity-2020-schwarzschild-precession'),
    kind: 'journal-article',
    authors: 'GRAVITY Collaboration',
    year: 2020,
    title: 'Detection of the Schwarzschild precession in the orbit of the star S2',
    source: 'Astronomy & Astrophysics 636, L5',
    doi: '10.1051/0004-6361/202037813',
    arxiv: '2004.07187',
    supports: 'Relativistic precession of S2’s orbit around Sgr A*.',
  },
  {
    id: referenceId('kormendy-ho-2013'),
    kind: 'review',
    authors: 'Kormendy, J. & Ho, L. C.',
    year: 2013,
    title: 'Coevolution (Or Not) of Supermassive Black Holes and Host Galaxies',
    source: 'Annual Review of Astronomy and Astrophysics 51, 511',
    doi: '10.1146/annurev-astro-082708-101811',
    arxiv: '1304.7762',
    supports:
      'The M–σ relation and the demographics of supermassive black holes in galaxy centres.',
  },
  {
    id: referenceId('eht-2019-v-physical-origin'),
    kind: 'journal-article',
    authors: 'Event Horizon Telescope Collaboration',
    year: 2019,
    title: 'First M87 Event Horizon Telescope Results. V. Physical Origin of the Asymmetric Ring',
    source: 'The Astrophysical Journal Letters 875, L5',
    doi: '10.3847/2041-8213/ab0f43',
    supports:
      'Interpretation of the observed ring as emission lensed around the photon sphere, and of the central dimming as the shadow.',
  },
  {
    id: referenceId('abbott-2020-gw190521'),
    kind: 'journal-article',
    authors: 'Abbott, R. et al. (LIGO Scientific and Virgo Collaborations)',
    year: 2020,
    title: 'GW190521: A Binary Black Hole Merger with a Total Mass of 150 M☉',
    source: 'Physical Review Letters 125, 101102',
    doi: '10.1103/PhysRevLett.125.101102',
    arxiv: '2009.01075',
    supports: 'A remnant of about 142 solar masses — the intermediate-mass range.',
  },
  {
    id: referenceId('nanograv-2023-gwb'),
    kind: 'journal-article',
    authors: 'Agazie, G. et al. (NANOGrav Collaboration)',
    year: 2023,
    title: 'The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background',
    source: 'The Astrophysical Journal Letters 951, L8',
    doi: '10.3847/2041-8213/acdac6',
    arxiv: '2306.16213',
    supports:
      'Pulsar-timing evidence for a nanohertz gravitational-wave background, plausibly from supermassive black-hole binaries.',
  },
];

const BY_ID = new Map(REFERENCES.map((reference) => [reference.id, reference]));

export function getReference(id: Reference['id']): Reference | undefined {
  return BY_ID.get(id);
}
