/**
 * The shared reference pool — seed set.
 *
 * These are the primary sources the first content phases will lean on. The pool
 * is intentionally small right now: it exists to prove the citation machinery
 * end-to-end, not to pre-empt the content work. Every entry below is a real,
 * published source; nothing here is a placeholder.
 *
 * Adding a reference: append a record, keep the id stable forever (ids appear in
 * saved links and review notes), and fill `supports` so a reviewer can check the
 * citation without reading the whole paper.
 */
import { referenceId, type Reference } from '../schema/reference';

export const REFERENCES: readonly Reference[] = [
  {
    id: referenceId('planck-2018-vi'),
    kind: 'journal-article',
    authors: 'Planck Collaboration',
    year: 2020,
    title: 'Planck 2018 results. VI. Cosmological parameters',
    source: 'Astronomy & Astrophysics 641, A6',
    doi: '10.1051/0004-6361/201833910',
    arxiv: '1807.06209',
    supports:
      'Base-ΛCDM parameters: age of the Universe, Hubble constant, matter and dark-energy densities.',
  },
  {
    id: referenceId('fixsen-2009-cmb-temperature'),
    kind: 'journal-article',
    authors: 'Fixsen, D. J.',
    year: 2009,
    title: 'The Temperature of the Cosmic Microwave Background',
    source: 'The Astrophysical Journal 707, 916',
    doi: '10.1088/0004-637X/707/2/916',
    arxiv: '0911.1955',
    supports: 'Present-day CMB monopole temperature.',
  },
  {
    id: referenceId('penzias-wilson-1965'),
    kind: 'journal-article',
    authors: 'Penzias, A. A. & Wilson, R. W.',
    year: 1965,
    title: 'A Measurement of Excess Antenna Temperature at 4080 Mc/s',
    source: 'The Astrophysical Journal 142, 419',
    doi: '10.1086/148307',
    supports: 'Discovery of the cosmic microwave background.',
  },
  {
    id: referenceId('hubble-1929'),
    kind: 'journal-article',
    authors: 'Hubble, E.',
    year: 1929,
    title: 'A Relation between Distance and Radial Velocity among Extra-Galactic Nebulae',
    source: 'Proceedings of the National Academy of Sciences 15, 168',
    doi: '10.1073/pnas.15.3.168',
    supports: 'The distance–redshift relation; first observational evidence for expansion.',
  },
  {
    id: referenceId('riess-1998'),
    kind: 'journal-article',
    authors: 'Riess, A. G. et al.',
    year: 1998,
    title:
      'Observational Evidence from Supernovae for an Accelerating Universe and a Cosmological Constant',
    source: 'The Astronomical Journal 116, 1009',
    doi: '10.1086/300499',
    arxiv: 'astro-ph/9805201',
    supports: 'Accelerating expansion from Type Ia supernovae.',
  },
  {
    id: referenceId('perlmutter-1999'),
    kind: 'journal-article',
    authors: 'Perlmutter, S. et al.',
    year: 1999,
    title: 'Measurements of Ω and Λ from 42 High-Redshift Supernovae',
    source: 'The Astrophysical Journal 517, 565',
    doi: '10.1086/307221',
    arxiv: 'astro-ph/9812133',
    supports: 'Independent supernova evidence for accelerating expansion.',
  },
  {
    id: referenceId('rubin-ford-1970'),
    kind: 'journal-article',
    authors: 'Rubin, V. C. & Ford, W. K.',
    year: 1970,
    title: 'Rotation of the Andromeda Nebula from a Spectroscopic Survey of Emission Regions',
    source: 'The Astrophysical Journal 159, 379',
    doi: '10.1086/150317',
    supports: 'Galaxy rotation curves that do not match the visible mass.',
  },
  {
    id: referenceId('einstein-1916-gr'),
    kind: 'journal-article',
    authors: 'Einstein, A.',
    year: 1916,
    title: 'Die Grundlage der allgemeinen Relativitätstheorie',
    source: 'Annalen der Physik 354, 769',
    doi: '10.1002/andp.19163540702',
    supports: 'The field equations of general relativity.',
  },
  {
    id: referenceId('newton-1687-principia'),
    kind: 'book',
    authors: 'Newton, I.',
    year: 1687,
    title: 'Philosophiæ Naturalis Principia Mathematica',
    source: 'Royal Society, London',
    supports: 'The three laws of motion and universal gravitation.',
  },
  {
    id: referenceId('ligo-2016-gw150914'),
    kind: 'journal-article',
    authors: 'Abbott, B. P. et al. (LIGO Scientific Collaboration and Virgo Collaboration)',
    year: 2016,
    title: 'Observation of Gravitational Waves from a Binary Black Hole Merger',
    source: 'Physical Review Letters 116, 061102',
    doi: '10.1103/PhysRevLett.116.061102',
    arxiv: '1602.03837',
    supports: 'First direct detection of gravitational waves; binary black hole merger.',
  },
  {
    id: referenceId('eht-2019-m87'),
    kind: 'journal-article',
    authors: 'Event Horizon Telescope Collaboration',
    year: 2019,
    title:
      'First M87 Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole',
    source: 'The Astrophysical Journal Letters 875, L1',
    doi: '10.3847/2041-8213/ab0ec7',
    supports: 'Horizon-scale image of the M87* black hole shadow.',
  },
  {
    id: referenceId('patterson-1956-age-of-earth'),
    kind: 'journal-article',
    authors: 'Patterson, C.',
    year: 1956,
    title: 'Age of meteorites and the earth',
    source: 'Geochimica et Cosmochimica Acta 10, 230',
    doi: '10.1016/0016-7037(56)90036-9',
    supports: 'Lead-isotope determination of the age of the Earth and meteorites.',
  },
  {
    id: referenceId('hublin-2017-jebel-irhoud'),
    kind: 'journal-article',
    authors: 'Hublin, J.-J. et al.',
    year: 2017,
    title: 'New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens',
    source: 'Nature 546, 289',
    doi: '10.1038/nature22336',
    supports: 'Earliest known Homo sapiens fossils and a pan-African origin model.',
  },
  {
    id: referenceId('codata-2018'),
    kind: 'review',
    authors: 'Tiesinga, E., Mohr, P. J., Newell, D. B. & Taylor, B. N.',
    year: 2021,
    title: 'CODATA recommended values of the fundamental physical constants: 2018',
    source: 'Reviews of Modern Physics 93, 025010',
    doi: '10.1103/RevModPhys.93.025010',
    supports: 'Values of the fundamental physical constants used throughout the platform.',
  },

  // ---- Added for Phase 1 (Cosmic Timeline) --------------------------------

  {
    id: referenceId('guth-1981-inflation'),
    kind: 'journal-article',
    authors: 'Guth, A. H.',
    year: 1981,
    title: 'Inflationary universe: A possible solution to the horizon and flatness problems',
    source: 'Physical Review D 23, 347',
    doi: '10.1103/PhysRevD.23.347',
    supports:
      'The original proposal of cosmic inflation and the problems it was designed to solve.',
  },
  {
    id: referenceId('alpher-bethe-gamow-1948'),
    kind: 'journal-article',
    authors: 'Alpher, R. A., Bethe, H. & Gamow, G.',
    year: 1948,
    title: 'The Origin of Chemical Elements',
    source: 'Physical Review 73, 803',
    doi: '10.1103/PhysRev.73.803',
    supports: 'The first quantitative treatment of element formation in a hot early Universe.',
  },
  {
    id: referenceId('cyburt-2016-bbn'),
    kind: 'review',
    authors: 'Cyburt, R. H., Fields, B. D., Olive, K. A. & Yeh, T.-H.',
    year: 2016,
    title: 'Big bang nucleosynthesis: Present status',
    source: 'Reviews of Modern Physics 88, 015004',
    doi: '10.1103/RevModPhys.88.015004',
    arxiv: '1505.01076',
    supports:
      'Predicted and observed primordial abundances of hydrogen, helium-4, deuterium and lithium-7, including the lithium problem.',
  },
  {
    id: referenceId('busza-2018-heavy-ion'),
    kind: 'review',
    authors: 'Busza, W., Rajagopal, K. & van der Schee, W.',
    year: 2018,
    title: 'Heavy Ion Collisions: The Big Picture and the Big Questions',
    source: 'Annual Review of Nuclear and Particle Science 68, 339',
    doi: '10.1146/annurev-nucl-101917-020852',
    arxiv: '1802.04801',
    supports:
      'Laboratory recreation of quark–gluon plasma, the state matter is thought to have been in during the first microseconds.',
  },
  {
    id: referenceId('b2fh-1957'),
    kind: 'journal-article',
    authors: 'Burbidge, E. M., Burbidge, G. R., Fowler, W. A. & Hoyle, F.',
    year: 1957,
    title: 'Synthesis of the Elements in Stars',
    source: 'Reviews of Modern Physics 29, 547',
    doi: '10.1103/RevModPhys.29.547',
    supports: 'The stellar origin of elements heavier than lithium.',
  },
  {
    id: referenceId('kenrick-crane-1997-land-plants'),
    kind: 'journal-article',
    authors: 'Kenrick, P. & Crane, P. R.',
    year: 1997,
    title: 'The origin and early evolution of plants on land',
    source: 'Nature 389, 33',
    doi: '10.1038/37918',
    supports: 'Fossil and phylogenetic evidence for the colonisation of land by plants.',
  },
  {
    id: referenceId('smoot-1992-cobe'),
    kind: 'journal-article',
    authors: 'Smoot, G. F. et al.',
    year: 1992,
    title: 'Structure in the COBE differential microwave radiometer first-year maps',
    source: 'The Astrophysical Journal 396, L1',
    doi: '10.1086/186504',
    supports: 'First detection of temperature anisotropies in the cosmic microwave background.',
  },
  {
    id: referenceId('bennett-2013-wmap9'),
    kind: 'journal-article',
    authors: 'Bennett, C. L. et al.',
    year: 2013,
    title:
      'Nine-Year Wilkinson Microwave Anisotropy Probe (WMAP) Observations: Final Maps and Results',
    source: 'The Astrophysical Journal Supplement Series 208, 20',
    doi: '10.1088/0067-0049/208/2/20',
    arxiv: '1212.5225',
    supports:
      'Independent CMB determination of cosmological parameters, including the epoch of recombination.',
  },
  {
    id: referenceId('bromm-larson-2004-first-stars'),
    kind: 'review',
    authors: 'Bromm, V. & Larson, R. B.',
    year: 2004,
    title: 'The First Stars',
    source: 'Annual Review of Astronomy and Astrophysics 42, 79',
    doi: '10.1146/annurev.astro.42.053102.134034',
    arxiv: 'astro-ph/0311019',
    supports: 'Theory of Population III star formation, expected masses and formation redshifts.',
  },
  {
    id: referenceId('stark-2016-first-billion-years'),
    kind: 'review',
    authors: 'Stark, D. P.',
    year: 2016,
    title: 'Galaxies in the First Billion Years After the Big Bang',
    source: 'Annual Review of Astronomy and Astrophysics 54, 761',
    doi: '10.1146/annurev-astro-081915-023417',
    supports: 'Observations of the earliest galaxies and the progress of cosmic reionization.',
  },
  {
    id: referenceId('curtis-lake-2023-jwst'),
    kind: 'journal-article',
    authors: 'Curtis-Lake, E. et al.',
    year: 2023,
    title: 'Spectroscopic confirmation of four metal-poor galaxies at z = 10.3–13.2',
    source: 'Nature Astronomy 7, 622',
    doi: '10.1038/s41550-023-01918-w',
    arxiv: '2212.04568',
    supports: 'JWST spectroscopic confirmation of galaxies within the first ~400 million years.',
  },
  {
    id: referenceId('springel-2005-millennium'),
    kind: 'journal-article',
    authors: 'Springel, V. et al.',
    year: 2005,
    title: 'Simulations of the formation, evolution and clustering of galaxies and quasars',
    source: 'Nature 435, 629',
    doi: '10.1038/nature03597',
    arxiv: 'astro-ph/0504097',
    supports:
      'Cosmological simulation reproducing the observed large-scale filamentary structure of galaxies.',
  },
  {
    id: referenceId('bouvier-wadhwa-2010-solar-system-age'),
    kind: 'journal-article',
    authors: 'Bouvier, A. & Wadhwa, M.',
    year: 2010,
    title:
      'The age of the Solar System redefined by the oldest Pb–Pb age of a meteoritic inclusion',
    source: 'Nature Geoscience 3, 637',
    doi: '10.1038/ngeo941',
    supports: 'Lead–lead age of a calcium–aluminium-rich inclusion: 4568.2 million years.',
  },
  {
    id: referenceId('canup-asphaug-2001-moon'),
    kind: 'journal-article',
    authors: 'Canup, R. M. & Asphaug, E.',
    year: 2001,
    title: "Origin of the Moon in a giant impact near the end of the Earth's formation",
    source: 'Nature 412, 708',
    doi: '10.1038/35089010',
    supports: 'The giant-impact model for the formation of the Moon.',
  },
  {
    id: referenceId('wilde-2001-jack-hills-zircons'),
    kind: 'journal-article',
    authors: 'Wilde, S. A., Valley, J. W., Peck, W. H. & Graham, C. M.',
    year: 2001,
    title:
      'Evidence from detrital zircons for the existence of continental crust and oceans on the Earth 4.4 Gyr ago',
    source: 'Nature 409, 175',
    doi: '10.1038/35051550',
    supports: 'Jack Hills zircons indicating liquid water and crust within ~150 Myr of formation.',
  },
  {
    id: referenceId('bell-2015-biogenic-carbon-zircon'),
    kind: 'journal-article',
    authors: 'Bell, E. A., Boehnke, P., Harrison, T. M. & Mao, W. L.',
    year: 2015,
    title: 'Potentially biogenic carbon preserved in a 4.1 billion-year-old zircon',
    source: 'Proceedings of the National Academy of Sciences 112, 14518',
    doi: '10.1073/pnas.1517557112',
    supports: 'Contested carbon-isotope evidence that has been interpreted as biogenic at 4.1 Ga.',
  },
  {
    id: referenceId('dodd-2017-hydrothermal-life'),
    kind: 'journal-article',
    authors: 'Dodd, M. S. et al.',
    year: 2017,
    title: "Evidence for early life in Earth's oldest hydrothermal vent precipitates",
    source: 'Nature 543, 60',
    doi: '10.1038/nature21377',
    supports: 'Claimed microfossils at 3.77–4.28 Ga; a disputed candidate for earliest life.',
  },
  {
    id: referenceId('lyons-2014-oxygen-rise'),
    kind: 'review',
    authors: 'Lyons, T. W., Reinhard, C. T. & Planavsky, N. J.',
    year: 2014,
    title: "The rise of oxygen in Earth's early ocean and atmosphere",
    source: 'Nature 506, 307',
    doi: '10.1038/nature13068',
    supports:
      'Reconstructed history of atmospheric oxygen, including the Great Oxidation Event and the Neoproterozoic rise.',
  },
  {
    id: referenceId('hoffman-1998-snowball-earth'),
    kind: 'journal-article',
    authors: 'Hoffman, P. F., Kaufman, A. J., Halverson, G. P. & Schrag, D. P.',
    year: 1998,
    title: 'A Neoproterozoic Snowball Earth',
    source: 'Science 281, 1342',
    doi: '10.1126/science.281.5381.1342',
    supports: 'The snowball-Earth hypothesis for global Neoproterozoic glaciation.',
  },
  {
    id: referenceId('knoll-2011-multicellularity'),
    kind: 'review',
    authors: 'Knoll, A. H.',
    year: 2011,
    title: 'The Multiple Origins of Complex Multicellularity',
    source: 'Annual Review of Earth and Planetary Sciences 39, 217',
    doi: '10.1146/annurev.earth.031208.100209',
    supports: 'Independent origins of complex multicellular life and their timing.',
  },
  {
    id: referenceId('erwin-2011-cambrian'),
    kind: 'journal-article',
    authors: 'Erwin, D. H. et al.',
    year: 2011,
    title:
      'The Cambrian conundrum: early divergence and later ecological success in the early history of animals',
    source: 'Science 334, 1091',
    doi: '10.1126/science.1206375',
    supports:
      'The mismatch between molecular divergence estimates and the fossil record of animal phyla.',
  },
  {
    id: referenceId('alvarez-1980-kpg'),
    kind: 'journal-article',
    authors: 'Alvarez, L. W., Alvarez, W., Asaro, F. & Michel, H. V.',
    year: 1980,
    title: 'Extraterrestrial Cause for the Cretaceous-Tertiary Extinction',
    source: 'Science 208, 1095',
    doi: '10.1126/science.208.4448.1095',
    supports: 'The iridium anomaly and the original impact hypothesis for the K-Pg extinction.',
  },
  {
    id: referenceId('schulte-2010-chicxulub'),
    kind: 'review',
    authors: 'Schulte, P. et al.',
    year: 2010,
    title: 'The Chicxulub Asteroid Impact and Mass Extinction at the Cretaceous-Paleogene Boundary',
    source: 'Science 327, 1214',
    doi: '10.1126/science.1177265',
    supports: 'Consensus review of the impact evidence and the timing of the extinction.',
  },
  {
    id: referenceId('brusatte-2015-dinosaur-extinction'),
    kind: 'review',
    authors: 'Brusatte, S. L. et al.',
    year: 2015,
    title: 'The extinction of the dinosaurs',
    source: 'Biological Reviews 90, 628',
    doi: '10.1111/brv.12128',
    supports:
      'State of the debate on dinosaur decline before the impact, and the survival of birds.',
  },
  {
    id: referenceId('oleary-2013-placental-mammals'),
    kind: 'journal-article',
    authors: "O'Leary, M. A. et al.",
    year: 2013,
    title: 'The Placental Mammal Ancestor and the Post–K-Pg Radiation of Placentals',
    source: 'Science 339, 662',
    doi: '10.1126/science.1229237',
    supports: 'Combined morphological and molecular reconstruction of the placental radiation.',
  },
  {
    id: referenceId('bloch-2007-primates'),
    kind: 'journal-article',
    authors: 'Bloch, J. I., Silcox, M. T., Boyer, D. M. & Sargis, E. J.',
    year: 2007,
    title:
      'New Paleocene skeletons and the relationship of plesiadapiforms to crown-clade primates',
    source: 'Proceedings of the National Academy of Sciences 104, 1159',
    doi: '10.1073/pnas.0610579104',
    supports: 'Early Paleocene fossils bearing on the origin of primates.',
  },
  {
    id: referenceId('brunet-2002-sahelanthropus'),
    kind: 'journal-article',
    authors: 'Brunet, M. et al.',
    year: 2002,
    title: 'A new hominid from the Upper Miocene of Chad, Central Africa',
    source: 'Nature 418, 145',
    doi: '10.1038/nature00879',
    supports: 'Sahelanthropus tchadensis at ~7 Ma, near the human–chimpanzee divergence.',
  },
  {
    id: referenceId('leakey-1995-australopithecus-anamensis'),
    kind: 'journal-article',
    authors: 'Leakey, M. G., Feibel, C. S., McDougall, I. & Walker, A.',
    year: 1995,
    title: 'New four-million-year-old hominid species from Kanapoi and Allia Bay, Kenya',
    source: 'Nature 376, 565',
    doi: '10.1038/376565a0',
    supports: 'Australopithecus anamensis and early evidence of hominin bipedality.',
  },
  {
    id: referenceId('villmoare-2015-early-homo'),
    kind: 'journal-article',
    authors: 'Villmoare, B. et al.',
    year: 2015,
    title: 'Early Homo at 2.8 Ma from Ledi-Geraru, Afar, Ethiopia',
    source: 'Science 347, 1352',
    doi: '10.1126/science.aaa1343',
    supports: 'The oldest well-dated fossil attributed to the genus Homo.',
  },
  {
    id: referenceId('bramble-lieberman-2004-endurance-running'),
    kind: 'journal-article',
    authors: 'Bramble, D. M. & Lieberman, D. E.',
    year: 2004,
    title: 'Endurance running and the evolution of Homo',
    source: 'Nature 432, 345',
    doi: '10.1038/nature03052',
    supports: 'Anatomical changes in Homo erectus associated with long-distance running.',
  },
  {
    id: referenceId('berger-2015-homo-naledi'),
    kind: 'journal-article',
    authors: 'Berger, L. R. et al.',
    year: 2015,
    title: 'Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa',
    source: 'eLife 4, e09560',
    doi: '10.7554/eLife.09560',
    supports:
      'A small-brained Homo species surviving alongside larger-brained ones; evidence that the hominin record is bushy.',
  },
  {
    id: referenceId('green-2010-neanderthal-genome'),
    kind: 'journal-article',
    authors: 'Green, R. E. et al.',
    year: 2010,
    title: 'A Draft Sequence of the Neandertal Genome',
    source: 'Science 328, 710',
    doi: '10.1126/science.1188021',
    supports: 'First evidence of Neanderthal ancestry in non-African modern human genomes.',
  },
  {
    id: referenceId('reich-2010-denisova'),
    kind: 'journal-article',
    authors: 'Reich, D. et al.',
    year: 2010,
    title: 'Genetic history of an archaic hominin group from Denisova Cave in Siberia',
    source: 'Nature 468, 1053',
    doi: '10.1038/nature09710',
    supports:
      'Identification of the Denisovans from DNA alone, and their ancestry in present-day Melanesians.',
  },
  {
    id: referenceId('prufer-2014-altai-neanderthal'),
    kind: 'journal-article',
    authors: 'Prüfer, K. et al.',
    year: 2014,
    title: 'The complete genome sequence of a Neanderthal from the Altai Mountains',
    source: 'Nature 505, 43',
    doi: '10.1038/nature12886',
    supports: 'High-coverage Neanderthal genome and quantified interbreeding with modern humans.',
  },
  {
    id: referenceId('vidal-2022-omo-kibish'),
    kind: 'journal-article',
    authors: 'Vidal, C. M. et al.',
    year: 2022,
    title: 'Age of the oldest known Homo sapiens from eastern Africa',
    source: 'Nature 601, 579',
    doi: '10.1038/s41586-021-04275-8',
    supports: 'Revised minimum age of ~233,000 years for the Omo Kibish Homo sapiens fossils.',
  },
  {
    id: referenceId('nielsen-2017-peopling-of-the-world'),
    kind: 'review',
    authors: 'Nielsen, R. et al.',
    year: 2017,
    title: 'Tracing the peopling of the world through genomics',
    source: 'Nature 541, 302',
    doi: '10.1038/nature21347',
    supports: 'Genomic evidence for the timing and routes of modern human dispersal.',
  },
  {
    id: referenceId('clarkson-2017-madjedbebe'),
    kind: 'journal-article',
    authors: 'Clarkson, C. et al.',
    year: 2017,
    title: 'Human occupation of northern Australia by 65,000 years ago',
    source: 'Nature 547, 306',
    doi: '10.1038/nature22968',
    supports: 'Archaeological dating of early modern human presence in Australia.',
  },
  {
    id: referenceId('zeder-2011-agriculture-origins'),
    kind: 'review',
    authors: 'Zeder, M. A.',
    year: 2011,
    title: 'The Origins of Agriculture in the Near East',
    source: 'Current Anthropology 52, S221',
    doi: '10.1086/659307',
    supports: 'Timing and process of plant and animal domestication in the Fertile Crescent.',
  },
  {
    id: referenceId('diamond-2002-domestication'),
    kind: 'journal-article',
    authors: 'Diamond, J.',
    year: 2002,
    title: 'Evolution, consequences and future of plant and animal domestication',
    source: 'Nature 418, 700',
    doi: '10.1038/nature01019',
    supports: 'Independent centres of domestication and their consequences.',
  },
  {
    id: referenceId('darwin-1859-origin'),
    kind: 'book',
    authors: 'Darwin, C.',
    year: 1859,
    title: 'On the Origin of Species by Means of Natural Selection',
    source: 'John Murray, London',
    supports: 'Descent with modification and branching common ancestry.',
  },
  {
    id: referenceId('riess-2022-sh0es'),
    kind: 'journal-article',
    authors: 'Riess, A. G. et al.',
    year: 2022,
    title:
      'A Comprehensive Measurement of the Local Value of the Hubble Constant with 1 km/s/Mpc Uncertainty from the Hubble Space Telescope and the SH0ES Team',
    source: 'The Astrophysical Journal Letters 934, L7',
    doi: '10.3847/2041-8213/ac5c5b',
    arxiv: '2112.04510',
    supports: 'Local distance-ladder value of H0 that is in tension with the CMB-derived value.',
  },
  {
    id: referenceId('ics-chart'),
    kind: 'agency-page',
    authors: 'International Commission on Stratigraphy',
    year: 2023,
    title: 'International Chronostratigraphic Chart',
    source: 'International Union of Geological Sciences',
    url: 'https://stratigraphy.org/chart',
    accessed: '2026-09-06',
    supports: 'Formal boundary ages for geological periods used throughout the timeline.',
  },

  // ---- Added for Phase 2 (Universe & Cosmology) ---------------------------

  {
    id: referenceId('lemaitre-1927'),
    kind: 'journal-article',
    authors: 'Lemaître, G.',
    year: 1927,
    title:
      'Un Univers homogène de masse constante et de rayon croissant rendant compte de la vitesse radiale des nébuleuses extra-galactiques',
    source: 'Annales de la Société Scientifique de Bruxelles A47, 49',
    url: 'https://ui.adsabs.harvard.edu/abs/1927ASSB...47...49L',
    accessed: '2026-09-06',
    supports:
      'The first derivation of an expanding-universe solution together with a linear velocity–distance relation.',
  },
  {
    id: referenceId('friedmann-1922'),
    kind: 'journal-article',
    authors: 'Friedmann, A.',
    year: 1922,
    title: 'Über die Krümmung des Raumes',
    source: 'Zeitschrift für Physik 10, 377',
    doi: '10.1007/BF01332580',
    supports: 'The dynamical equations governing an expanding homogeneous universe.',
  },
  {
    id: referenceId('linde-1982-new-inflation'),
    kind: 'journal-article',
    authors: 'Linde, A. D.',
    year: 1982,
    title:
      'A new inflationary universe scenario: A possible solution of the horizon, flatness, homogeneity, isotropy and primordial monopole problems',
    source: 'Physics Letters B 108, 389',
    doi: '10.1016/0370-2693(82)91219-9',
    supports: 'The slow-roll formulation of inflation that made the framework workable.',
  },
  {
    id: referenceId('bicep-keck-2021'),
    kind: 'journal-article',
    authors: 'BICEP/Keck Collaboration (Ade, P. A. R. et al.)',
    year: 2021,
    title:
      'Improved Constraints on Primordial Gravitational Waves using Planck, WMAP, and BICEP/Keck Observations through the 2018 Observing Season',
    source: 'Physical Review Letters 127, 151301',
    doi: '10.1103/PhysRevLett.127.151301',
    arxiv: '2110.00483',
    supports:
      'The current upper limit on the tensor-to-scalar ratio, r < 0.036 — inflation’s signature prediction remains undetected.',
  },
  {
    id: referenceId('ijjas-steinhardt-loeb-2013'),
    kind: 'journal-article',
    authors: 'Ijjas, A., Steinhardt, P. J. & Loeb, A.',
    year: 2013,
    title: 'Inflationary paradigm in trouble after Planck2013',
    source: 'Physics Letters B 723, 261',
    doi: '10.1016/j.physletb.2013.05.023',
    arxiv: '1304.2785',
    supports:
      'A critique of inflation from within the field: the framework’s flexibility weakens its predictive power.',
  },
  {
    id: referenceId('mather-1994-cobe-firas'),
    kind: 'journal-article',
    authors: 'Mather, J. C. et al.',
    year: 1994,
    title: 'Measurement of the cosmic microwave background spectrum by the COBE FIRAS instrument',
    source: 'The Astrophysical Journal 420, 439',
    doi: '10.1086/173574',
    supports:
      'The CMB is a blackbody to within 50 parts per million — the most precise blackbody spectrum ever measured.',
  },
  {
    id: referenceId('gamow-1948'),
    kind: 'journal-article',
    authors: 'Gamow, G.',
    year: 1948,
    title: 'The Evolution of the Universe',
    source: 'Nature 162, 680',
    doi: '10.1038/162680a0',
    supports: 'The prediction that a hot early universe would leave behind relic radiation.',
  },
  {
    id: referenceId('zwicky-1933'),
    kind: 'journal-article',
    authors: 'Zwicky, F.',
    year: 1933,
    title: 'Die Rotverschiebung von extragalaktischen Nebeln',
    source: 'Helvetica Physica Acta 6, 110',
    url: 'https://ui.adsabs.harvard.edu/abs/1933AcHPh...6..110Z',
    accessed: '2026-09-06',
    supports:
      'The first evidence for missing mass: galaxy velocities in the Coma cluster far exceed what its visible matter can bind.',
  },
  {
    id: referenceId('clowe-2006-bullet-cluster'),
    kind: 'journal-article',
    authors: 'Clowe, D. et al.',
    year: 2006,
    title: 'A Direct Empirical Proof of the Existence of Dark Matter',
    source: 'The Astrophysical Journal Letters 648, L109',
    doi: '10.1086/508162',
    arxiv: 'astro-ph/0608407',
    supports:
      'In the Bullet Cluster the lensing mass is separated from the hot gas, which is hard to explain by modifying gravity alone.',
  },
  {
    id: referenceId('lux-zeplin-2023'),
    kind: 'journal-article',
    authors: 'LZ Collaboration (Aalbers, J. et al.)',
    year: 2023,
    title: 'First Dark Matter Search Results from the LUX-ZEPLIN (LZ) Experiment',
    source: 'Physical Review Letters 131, 041002',
    doi: '10.1103/PhysRevLett.131.041002',
    arxiv: '2207.03764',
    supports:
      'A leading direct-detection search returning null results: no dark-matter particle has been detected.',
  },
  {
    id: referenceId('bertone-hooper-2018-history'),
    kind: 'review',
    authors: 'Bertone, G. & Hooper, D.',
    year: 2018,
    title: 'History of dark matter',
    source: 'Reviews of Modern Physics 90, 045002',
    doi: '10.1103/RevModPhys.90.045002',
    arxiv: '1605.04909',
    supports: 'A review of the evidence for dark matter and of the candidates proposed for it.',
  },
  {
    id: referenceId('weinberg-1989-cc-problem'),
    kind: 'review',
    authors: 'Weinberg, S.',
    year: 1989,
    title: 'The cosmological constant problem',
    source: 'Reviews of Modern Physics 61, 1',
    doi: '10.1103/RevModPhys.61.1',
    supports:
      'The mismatch between the observed vacuum energy density and quantum field theory estimates.',
  },
  {
    id: referenceId('brout-2022-pantheon-plus'),
    kind: 'journal-article',
    authors: 'Brout, D. et al.',
    year: 2022,
    title: 'The Pantheon+ Analysis: Cosmological Constraints',
    source: 'The Astrophysical Journal 938, 110',
    doi: '10.3847/1538-4357/ac8e04',
    arxiv: '2202.04077',
    supports:
      'A compilation of 1550 Type Ia supernovae constraining the expansion history and the dark-energy equation of state.',
  },
  {
    id: referenceId('eisenstein-2005-bao'),
    kind: 'journal-article',
    authors: 'Eisenstein, D. J. et al.',
    year: 2005,
    title:
      'Detection of the Baryon Acoustic Peak in the Large-Scale Correlation Function of SDSS Luminous Red Galaxies',
    source: 'The Astrophysical Journal 633, 560',
    doi: '10.1086/466512',
    arxiv: 'astro-ph/0501171',
    supports:
      'Baryon acoustic oscillations detected in the galaxy distribution — a standard ruler independent of supernovae.',
  },
  {
    id: referenceId('desi-2024-bao'),
    kind: 'journal-article',
    authors: 'DESI Collaboration (Adame, A. G. et al.)',
    year: 2025,
    title:
      'DESI 2024 VI: cosmological constraints from the measurements of baryon acoustic oscillations',
    source: 'Journal of Cosmology and Astroparticle Physics 2025(02), 021',
    doi: '10.1088/1475-7516/2025/02/021',
    arxiv: '2404.03002',
    supports:
      'Baryon acoustic oscillation measurements that, combined with other data, hint at dark energy possibly evolving with time.',
  },
  {
    id: referenceId('gott-2005-map-of-the-universe'),
    kind: 'journal-article',
    authors: 'Gott, J. R. et al.',
    year: 2005,
    title: 'A Map of the Universe',
    source: 'The Astrophysical Journal 624, 463',
    doi: '10.1086/428890',
    arxiv: 'astro-ph/0310571',
    supports:
      'Comoving distance to the particle horizon: the observable Universe is about 46 billion light-years in radius.',
  },
  {
    id: referenceId('geller-huchra-1989'),
    kind: 'journal-article',
    authors: 'Geller, M. J. & Huchra, J. P.',
    year: 1989,
    title: 'Mapping the Universe',
    source: 'Science 246, 897',
    doi: '10.1126/science.246.4932.897',
    supports:
      'The first redshift surveys revealing that galaxies lie on sheets and filaments surrounding vast voids.',
  },
  {
    id: referenceId('vogelsberger-2014-illustris'),
    kind: 'journal-article',
    authors: 'Vogelsberger, M. et al.',
    year: 2014,
    title: 'Properties of galaxies reproduced by a hydrodynamic simulation',
    source: 'Nature 509, 177',
    doi: '10.1038/nature13316',
    arxiv: '1405.1418',
    supports:
      'Cosmological simulations reproduce observed large-scale structure and galaxy populations under ΛCDM.',
  },
  {
    id: referenceId('planck-2018-x-inflation'),
    kind: 'journal-article',
    authors: 'Planck Collaboration',
    year: 2020,
    title: 'Planck 2018 results. X. Constraints on inflation',
    source: 'Astronomy & Astrophysics 641, A10',
    doi: '10.1051/0004-6361/201833887',
    arxiv: '1807.06211',
    supports:
      'Measured scalar spectral index and limits on primordial gravitational waves and non-Gaussianity.',
  },
  {
    id: referenceId('pdg-2024'),
    kind: 'review',
    authors: 'Particle Data Group (Navas, S. et al.)',
    year: 2024,
    title: 'Review of Particle Physics',
    source: 'Physical Review D 110, 030001',
    doi: '10.1103/PhysRevD.110.030001',
    supports:
      'Reference values for particle properties and for the cosmological parameters reviewed by the PDG.',
  },
  {
    id: referenceId('freedman-2021-h0'),
    kind: 'journal-article',
    authors: 'Freedman, W. L.',
    year: 2021,
    title: 'Measurements of the Hubble Constant: Tensions in Perspective',
    source: 'The Astrophysical Journal 919, 16',
    doi: '10.3847/1538-4357/ac0e95',
    arxiv: '2106.15656',
    supports:
      'An independent distance-ladder calibration giving a value between the CMB and SH0ES results.',
  },
];

const BY_ID = new Map(REFERENCES.map((reference) => [reference.id, reference]));

export function getReference(id: Reference['id']): Reference | undefined {
  return BY_ID.get(id);
}
