/**
 * References for the Philosophical Lens of Human Evolution.
 *
 * Philosophy cites differently from science, and the difference matters here.
 * A scientific claim is supported by a result; a philosophical claim is
 * supported by an *argument*, and the argument lives in a text. So the backbone
 * of this pool is primary texts — the works in which the arguments were
 * actually made — with three supporting layers around them:
 *
 *   · Journal articles, where a twentieth-century argument first appeared in
 *     its canonical form (Nagel on bats, Frankfurt on alternate possibilities,
 *     Strawson on reactive attitudes).
 *   · Stanford Encyclopedia of Philosophy entries, used where a reader needs a
 *     survey of a live dispute rather than one side of it. The SEP is peer
 *     reviewed and revised, which is why it is cited here and general
 *     encyclopedias are not.
 *   · A small number of empirical papers, used *only* where a philosophical
 *     topic makes an empirical claim about what experiments found — never as
 *     the support for a philosophical conclusion.
 *
 * Two deliberate absences. There are no quotations anywhere in this lens, so
 * nothing here is cited to authenticate a quotation. And no scientific result
 * is offered as settling a philosophical question; where an experiment appears,
 * the topic that cites it says explicitly what the experiment can and cannot
 * decide.
 *
 * Dates: for translated classics the `year` is the year of the edition cited,
 * with the original date given in the title or source line, because that is the
 * edition a reader can actually pick up.
 */
import { referenceId, type Reference } from '../schema/reference';

const SEP_ACCESSED = '2026-09-11';

export const PHILOSOPHY_REFERENCES: readonly Reference[] = [
  /* ------------------------------------------------- primary texts: ancient */
  {
    id: referenceId('plato-republic'),
    kind: 'book',
    authors: 'Plato (trans. G. M. A. Grube, rev. C. D. C. Reeve)',
    year: 1992,
    title: 'Republic',
    source: 'Hackett Publishing (composed c. 375 BCE)',
    supports: 'The allegory of the cave, Books VI–VII; the divided line.',
  },
  {
    id: referenceId('aristotle-nicomachean-ethics'),
    kind: 'book',
    authors: 'Aristotle (trans. T. Irwin)',
    year: 1999,
    title: 'Nicomachean Ethics',
    source: 'Hackett Publishing, 2nd edition (composed c. 340 BCE)',
    supports:
      'Virtue as a stable disposition, the doctrine of the mean, habituation, and eudaimonia as activity rather than feeling.',
  },
  {
    id: referenceId('epictetus-discourses'),
    kind: 'book',
    authors: 'Epictetus (trans. R. Dobbin)',
    year: 2008,
    title: 'Discourses and Selected Writings',
    source: 'Penguin Classics (composed c. 108 CE)',
    supports: 'The Stoic division between what is and is not in our power.',
  },
  {
    id: referenceId('marcus-aurelius-meditations'),
    kind: 'book',
    authors: 'Marcus Aurelius (trans. M. Hammond)',
    year: 2006,
    title: 'Meditations',
    source: 'Penguin Classics (composed c. 180 CE)',
    supports: 'Stoic practice as something rehearsed daily rather than concluded once.',
  },
  {
    id: referenceId('analects-confucius'),
    kind: 'book',
    authors: 'Confucius (trans. E. Slingerland)',
    year: 2003,
    title: 'Analects: With Selections from Traditional Commentaries',
    source: 'Hackett Publishing (compiled c. 5th–3rd century BCE)',
    supports: 'Ethical cultivation through role, ritual and practice rather than through rules.',
  },
  {
    id: referenceId('mengzi'),
    kind: 'book',
    authors: 'Mengzi (trans. B. W. Van Norden)',
    year: 2008,
    title: 'Mengzi: With Selections from Traditional Commentaries',
    source: 'Hackett Publishing (composed c. 300 BCE)',
    supports: 'The argument that moral response has natural roots that must still be cultivated.',
  },
  {
    id: referenceId('zhuangzi-ziporyn'),
    kind: 'book',
    authors: 'Zhuangzi (trans. B. Ziporyn)',
    year: 2020,
    title: 'Zhuangzi: The Complete Writings',
    source: 'Hackett Publishing (composed c. 3rd century BCE)',
    supports: 'Scepticism about the fixity of perspective, including the butterfly passage.',
  },
  {
    id: referenceId('upanishads-olivelle'),
    kind: 'book',
    authors: 'Olivelle, P. (trans.)',
    year: 1996,
    title: 'Upaniṣads',
    source: 'Oxford World’s Classics (composed c. 800–300 BCE)',
    supports: 'Ātman as an enduring self — the position Buddhist anattā was formulated against.',
  },
  {
    id: referenceId('bodhi-2000-connected-discourses'),
    kind: 'book',
    authors: 'Bodhi, Bhikkhu (trans.)',
    year: 2000,
    title: 'The Connected Discourses of the Buddha: A Translation of the Saṃyutta Nikāya',
    source: 'Wisdom Publications',
    supports:
      'The Anattalakkhaṇa Sutta (SN 22.59): the five aggregates argument for non-self, and its form as an argument about control and impermanence rather than a denial of existence.',
  },
  {
    id: referenceId('milindapanha-rhys-davids'),
    kind: 'book',
    authors: 'Rhys Davids, T. W. (trans.)',
    year: 1890,
    title: 'The Questions of King Milinda',
    source: 'Sacred Books of the East, Vol. 35, Clarendon Press (composed c. 100 BCE)',
    supports: 'The chariot analogy: a composite thing named without a separate essence behind it.',
  },
  {
    id: referenceId('nagarjuna-garfield'),
    kind: 'book',
    authors: 'Nāgārjuna (trans. and commentary J. L. Garfield)',
    year: 1995,
    title: 'The Fundamental Wisdom of the Middle Way: Nāgārjuna’s Mūlamadhyamakakārikā',
    source: 'Oxford University Press (composed c. 150 CE)',
    supports:
      'Emptiness as dependent origination, and the explicit rejection of the reading that emptiness means nothing exists.',
  },

  /* ------------------------------------------------- primary texts: modern */
  {
    id: referenceId('descartes-meditations'),
    kind: 'book',
    authors: 'Descartes, R. (trans. J. Cottingham)',
    year: 1996,
    title: 'Meditations on First Philosophy, with Selections from the Objections and Replies',
    source: 'Cambridge University Press (first published 1641)',
    supports:
      'Methodical doubt, the dream argument, the deceiver argument, and the cogito as the point doubt cannot reach.',
  },
  {
    id: referenceId('descartes-discourse'),
    kind: 'book',
    authors: 'Descartes, R. (trans. J. Cottingham, R. Stoothoff & D. Murdoch)',
    year: 1985,
    title: 'Discourse on the Method, in The Philosophical Writings of Descartes, Vol. I',
    source: 'Cambridge University Press (first published 1637)',
    supports: 'The method of doubt stated before the Meditations developed it.',
  },
  {
    id: referenceId('locke-essay'),
    kind: 'book',
    authors: 'Locke, J. (ed. P. H. Nidditch)',
    year: 1975,
    title: 'An Essay Concerning Human Understanding',
    source: 'Clarendon Press (first published 1689; identity chapter added 1694)',
    supports:
      'Book II ch. 27: personal identity as continuity of consciousness, and the distinction between the man, the person and the substance.',
  },
  {
    id: referenceId('hume-treatise'),
    kind: 'book',
    authors: 'Hume, D. (ed. D. F. Norton & M. J. Norton)',
    year: 2000,
    title: 'A Treatise of Human Nature',
    source: 'Oxford University Press (first published 1739–40)',
    supports:
      'The bundle theory of the self (I.iv.6), the problem of induction (I.iii), and the is–ought passage (III.i.1).',
  },
  {
    id: referenceId('hume-enquiry'),
    kind: 'book',
    authors: 'Hume, D. (ed. T. L. Beauchamp)',
    year: 1999,
    title: 'An Enquiry Concerning Human Understanding',
    source: 'Oxford University Press (first published 1748)',
    supports:
      'The sceptical argument about causation and expectation, and the compatibilist account of liberty and necessity.',
  },
  {
    id: referenceId('kant-critique-pure-reason'),
    kind: 'book',
    authors: 'Kant, I. (trans. P. Guyer & A. W. Wood)',
    year: 1998,
    title: 'Critique of Pure Reason',
    source: 'Cambridge University Press (first published 1781, 2nd edition 1787)',
    supports:
      'The distinction between appearances and things in themselves; space and time as forms of intuition.',
  },
  {
    id: referenceId('kant-groundwork'),
    kind: 'book',
    authors: 'Kant, I. (trans. M. Gregor)',
    year: 1998,
    title: 'Groundwork of the Metaphysics of Morals',
    source: 'Cambridge University Press (first published 1785)',
    supports:
      'The categorical imperative in its universal-law and humanity formulations; the good will; duty versus inclination.',
  },
  {
    id: referenceId('bentham-principles'),
    kind: 'book',
    authors: 'Bentham, J. (ed. J. H. Burns & H. L. A. Hart)',
    year: 1996,
    title: 'An Introduction to the Principles of Morals and Legislation',
    source: 'Clarendon Press (first published 1789)',
    supports: 'The principle of utility, and punishment justified only by its future good.',
  },
  {
    id: referenceId('mill-utilitarianism'),
    kind: 'book',
    authors: 'Mill, J. S. (ed. R. Crisp)',
    year: 1998,
    title: 'Utilitarianism',
    source: 'Oxford University Press (first published 1863)',
    supports:
      'Utility as the criterion of right action, and the distinction between higher and lower pleasures.',
  },
  {
    id: referenceId('schopenhauer-world-as-will'),
    kind: 'book',
    authors: 'Schopenhauer, A. (trans. J. Norman, A. Welchman & C. Janaway)',
    year: 2010,
    title: 'The World as Will and Representation, Volume 1',
    source: 'Cambridge University Press (first published 1818)',
    supports:
      'Willing as prior to and largely opaque to the intellect; the claim that one can do what one wills but not will what one wills.',
  },
  {
    id: referenceId('kierkegaard-either-or'),
    kind: 'book',
    authors: 'Kierkegaard, S. (trans. H. V. Hong & E. H. Hong)',
    year: 1987,
    title: 'Either/Or, Part II',
    source: 'Princeton University Press (first published 1843)',
    supports: 'Choice as constitutive of a self rather than as selection among options.',
  },
  {
    id: referenceId('nietzsche-genealogy'),
    kind: 'book',
    authors: 'Nietzsche, F. (trans. M. Clark & A. J. Swensen)',
    year: 1998,
    title: 'On the Genealogy of Morality',
    source: 'Hackett Publishing (first published 1887)',
    supports:
      'The historical method applied to moral concepts; the good/bad and good/evil contrast; the analysis of guilt, debt and punishment.',
  },
  {
    id: referenceId('nietzsche-gay-science'),
    kind: 'book',
    authors: 'Nietzsche, F. (ed. B. Williams, trans. J. Nauckhoff)',
    year: 2001,
    title: 'The Gay Science',
    source: 'Cambridge University Press (first published 1882, expanded 1887)',
    supports: 'The death of God passage and the eternal recurrence thought experiment.',
  },
  {
    id: referenceId('nietzsche-zarathustra'),
    kind: 'book',
    authors: 'Nietzsche, F. (ed. A. Del Caro & R. Pippin)',
    year: 2006,
    title: 'Thus Spoke Zarathustra',
    source: 'Cambridge University Press (first published 1883–85)',
    supports: 'The Übermensch, presented as a figure in a literary work rather than a doctrine.',
  },
  {
    id: referenceId('heidegger-being-time'),
    kind: 'book',
    authors: 'Heidegger, M. (trans. J. Macquarrie & E. Robinson)',
    year: 1962,
    title: 'Being and Time',
    source: 'Blackwell (first published 1927)',
    supports:
      'Everyday absorption in “the they”, and being-towards-death as a condition of authentic existence.',
  },
  {
    id: referenceId('camus-sisyphus'),
    kind: 'book',
    authors: 'Camus, A. (trans. J. O’Brien)',
    year: 1991,
    title: 'The Myth of Sisyphus and Other Essays',
    source: 'Vintage International (first published 1942)',
    supports:
      'The absurd as a relation between human demand for meaning and the world’s silence; the rejection of both suicide and the philosophical leap.',
  },
  {
    id: referenceId('sartre-being-nothingness'),
    kind: 'book',
    authors: 'Sartre, J.-P. (trans. H. E. Barnes)',
    year: 1956,
    title: 'Being and Nothingness',
    source: 'Philosophical Library (first published 1943)',
    supports: 'Radical freedom, bad faith, and facticity as the situation freedom works within.',
  },
  {
    id: referenceId('sartre-existentialism-humanism'),
    kind: 'book',
    authors: 'Sartre, J.-P. (trans. C. Macomber)',
    year: 2007,
    title: 'Existentialism Is a Humanism',
    source: 'Yale University Press (lecture delivered 1945, published 1946)',
    supports:
      'Existence preceding essence, and the claim that choosing for oneself is choosing an image of what a person should be.',
  },
  {
    id: referenceId('beauvoir-ethics-ambiguity'),
    kind: 'book',
    authors: 'Beauvoir, S. de (trans. B. Frechtman)',
    year: 1948,
    title: 'The Ethics of Ambiguity',
    source: 'Philosophical Library (first published 1947)',
    supports:
      'Freedom as situated and dependent on the freedom of others — the existentialist reply to the charge that radical freedom licenses anything.',
  },
  {
    id: referenceId('beauvoir-second-sex'),
    kind: 'book',
    authors: 'Beauvoir, S. de (trans. C. Borde & S. Malovany-Chevallier)',
    year: 2010,
    title: 'The Second Sex',
    source: 'Alfred A. Knopf (first published 1949)',
    supports:
      'The analysis of a self formed under conditions it did not choose, and of situation as constraint rather than excuse.',
  },
  {
    id: referenceId('frankl-mans-search'),
    kind: 'book',
    authors: 'Frankl, V. E. (trans. I. Lasch)',
    year: 2006,
    title: 'Man’s Search for Meaning',
    source: 'Beacon Press (first published 1946)',
    supports:
      'The claim that meaning is found in a response to circumstances rather than supplied by them.',
  },

  /* ---------------------------------------------- twentieth century onward */
  {
    id: referenceId('parfit-reasons-persons'),
    kind: 'book',
    authors: 'Parfit, D.',
    year: 1984,
    title: 'Reasons and Persons',
    source: 'Oxford University Press',
    supports:
      'Teletransportation and fission cases; the reductionist view of personal identity; the argument that identity is not what matters in survival.',
  },
  {
    id: referenceId('moore-principia-ethica'),
    kind: 'book',
    authors: 'Moore, G. E.',
    year: 1903,
    title: 'Principia Ethica',
    source: 'Cambridge University Press',
    supports: 'The open-question argument and the charge of a naturalistic fallacy.',
  },
  {
    id: referenceId('mackie-ethics'),
    kind: 'book',
    authors: 'Mackie, J. L.',
    year: 1977,
    title: 'Ethics: Inventing Right and Wrong',
    source: 'Penguin Books',
    supports:
      'The error theory; the arguments from relativity and from queerness against objective moral values.',
  },
  {
    id: referenceId('anscombe-1958-modern-moral-philosophy'),
    kind: 'journal-article',
    authors: 'Anscombe, G. E. M.',
    year: 1958,
    title: 'Modern Moral Philosophy',
    source: 'Philosophy 33, 1–19',
    doi: '10.1017/S0031819100037943',
    supports:
      'The argument that obligation-centred ethics is a survival of a framework it abandoned, and the revival of virtue as a category.',
  },
  {
    id: referenceId('macintyre-after-virtue'),
    kind: 'book',
    authors: 'MacIntyre, A.',
    year: 1981,
    title: 'After Virtue: A Study in Moral Theory',
    source: 'University of Notre Dame Press',
    supports:
      'The diagnosis that modern moral disagreement is interminable because it draws on incompatible inherited fragments.',
  },
  {
    id: referenceId('hursthouse-virtue-ethics'),
    kind: 'book',
    authors: 'Hursthouse, R.',
    year: 1999,
    title: 'On Virtue Ethics',
    source: 'Oxford University Press',
    supports:
      'Virtue ethics stated as an action-guiding theory, and its reply to the charge that it gives no advice.',
  },
  {
    id: referenceId('williams-moral-luck'),
    kind: 'book',
    authors: 'Williams, B.',
    year: 1981,
    title: 'Moral Luck: Philosophical Papers 1973–1980',
    source: 'Cambridge University Press',
    supports:
      'The title essay: retrospective justification, agent-regret, and the pressure luck puts on the idea that morality is immune to fortune.',
  },
  {
    id: referenceId('nagel-mortal-questions'),
    kind: 'book',
    authors: 'Nagel, T.',
    year: 1979,
    title: 'Mortal Questions',
    source: 'Cambridge University Press',
    supports:
      'The essays “Moral Luck”, “The Absurd”, “Death” and “What Is It Like to Be a Bat?” collected together.',
  },
  {
    id: referenceId('nagel-1971-absurd'),
    kind: 'journal-article',
    authors: 'Nagel, T.',
    year: 1971,
    title: 'The Absurd',
    source: 'The Journal of Philosophy 68, 716–727',
    doi: '10.2307/2024942',
    supports:
      'The absurd located in a collision between seriousness and the capacity to step back from it — a different account from Camus’s.',
  },
  {
    id: referenceId('nagel-1974-bat'),
    kind: 'journal-article',
    authors: 'Nagel, T.',
    year: 1974,
    title: 'What Is It Like to Be a Bat?',
    source: 'The Philosophical Review 83, 435–450',
    doi: '10.2307/2183914',
    supports:
      'The subjective character of experience, and the argument that an objective description leaves a point of view unaccounted for.',
  },
  {
    id: referenceId('jackson-1982-epiphenomenal-qualia'),
    kind: 'journal-article',
    authors: 'Jackson, F.',
    year: 1982,
    title: 'Epiphenomenal Qualia',
    source: 'The Philosophical Quarterly 32, 127–136',
    doi: '10.2307/2960077',
    supports: 'The knowledge argument — Mary the colour scientist.',
  },
  {
    id: referenceId('chalmers-1995-facing-up'),
    kind: 'journal-article',
    authors: 'Chalmers, D. J.',
    year: 1995,
    title: 'Facing Up to the Problem of Consciousness',
    source: 'Journal of Consciousness Studies 2, 200–219',
    url: 'https://consc.net/papers/facing.html',
    accessed: SEP_ACCESSED,
    supports: 'The formulation of the hard problem and its separation from the easy problems.',
  },
  {
    id: referenceId('chalmers-conscious-mind'),
    kind: 'book',
    authors: 'Chalmers, D. J.',
    year: 1996,
    title: 'The Conscious Mind: In Search of a Fundamental Theory',
    source: 'Oxford University Press',
    supports: 'The conceivability argument, philosophical zombies, and property dualism.',
  },
  {
    id: referenceId('dennett-consciousness-explained'),
    kind: 'book',
    authors: 'Dennett, D. C.',
    year: 1991,
    title: 'Consciousness Explained',
    source: 'Little, Brown and Company',
    supports:
      'The deflationary reply: that the hard problem rests on an illusion about what needs explaining.',
  },
  {
    id: referenceId('searle-1980-minds-brains-programs'),
    kind: 'journal-article',
    authors: 'Searle, J. R.',
    year: 1980,
    title: 'Minds, Brains, and Programs',
    source: 'Behavioral and Brain Sciences 3, 417–424',
    doi: '10.1017/S0140525X00005756',
    supports: 'The Chinese Room argument against understanding by symbol manipulation alone.',
  },
  {
    id: referenceId('frankfurt-1969-alternate-possibilities'),
    kind: 'journal-article',
    authors: 'Frankfurt, H. G.',
    year: 1969,
    title: 'Alternate Possibilities and Moral Responsibility',
    source: 'The Journal of Philosophy 66, 829–839',
    doi: '10.2307/2023833',
    supports:
      'The counterexample against the principle that responsibility requires the ability to do otherwise.',
  },
  {
    id: referenceId('frankfurt-1971-freedom-of-the-will'),
    kind: 'journal-article',
    authors: 'Frankfurt, H. G.',
    year: 1971,
    title: 'Freedom of the Will and the Concept of a Person',
    source: 'The Journal of Philosophy 68, 5–20',
    doi: '10.2307/2024717',
    supports:
      'The hierarchical account: freedom as agreement between what one wants and what one wants to want.',
  },
  {
    id: referenceId('strawson-pf-1962-freedom-resentment'),
    kind: 'book',
    authors: 'Strawson, P. F.',
    year: 2008,
    title: 'Freedom and Resentment, in Freedom and Resentment and Other Essays',
    source: 'Routledge (first published in Proceedings of the British Academy 48, 1962)',
    supports:
      'Responsibility grounded in the reactive attitudes, and the claim that no general thesis could rationally dislodge them.',
  },
  {
    id: referenceId('strawson-g-1994-impossibility'),
    kind: 'journal-article',
    authors: 'Strawson, G.',
    year: 1994,
    title: 'The Impossibility of Moral Responsibility',
    source: 'Philosophical Studies 75, 5–24',
    doi: '10.1007/BF00989879',
    supports:
      'The Basic Argument: that self-creation would be required for ultimate responsibility, and that it leads to a regress.',
  },
  {
    id: referenceId('dennett-elbow-room'),
    kind: 'book',
    authors: 'Dennett, D. C.',
    year: 1984,
    title: 'Elbow Room: The Varieties of Free Will Worth Wanting',
    source: 'MIT Press',
    supports:
      'The compatibilist case that the freedom people care about does not require exemption from causation.',
  },
  {
    id: referenceId('dennett-freedom-evolves'),
    kind: 'book',
    authors: 'Dennett, D. C.',
    year: 2003,
    title: 'Freedom Evolves',
    source: 'Viking Press',
    supports:
      'The argument that self-control is a capacity that can be built and improved, not a metaphysical exemption.',
  },
  {
    id: referenceId('kane-significance-free-will'),
    kind: 'book',
    authors: 'Kane, R.',
    year: 1996,
    title: 'The Significance of Free Will',
    source: 'Oxford University Press',
    supports:
      'A libertarian account that tries to answer the randomness objection through self-forming actions.',
  },
  {
    id: referenceId('pereboom-living-without-free-will'),
    kind: 'book',
    authors: 'Pereboom, D.',
    year: 2001,
    title: 'Living Without Free Will',
    source: 'Cambridge University Press',
    supports:
      'Hard incompatibilism, and the argument that abandoning desert-based blame need not be destructive.',
  },
  {
    id: referenceId('fischer-ravizza-responsibility-control'),
    kind: 'book',
    authors: 'Fischer, J. M. & Ravizza, M.',
    year: 1998,
    title: 'Responsibility and Control: A Theory of Moral Responsibility',
    source: 'Cambridge University Press',
    supports:
      'Guidance control and reasons-responsiveness as the conditions of responsibility, with ownership of the mechanism.',
  },
  {
    id: referenceId('wolf-freedom-within-reason'),
    kind: 'book',
    authors: 'Wolf, S.',
    year: 1990,
    title: 'Freedom Within Reason',
    source: 'Oxford University Press',
    supports:
      'The Reason View: freedom as the ability to act in accordance with reasons one could recognise as good.',
  },
  {
    id: referenceId('wolf-meaning-in-life'),
    kind: 'book',
    authors: 'Wolf, S.',
    year: 2010,
    title: 'Meaning in Life and Why It Matters',
    source: 'Princeton University Press',
    supports:
      'The hybrid view: meaning arises where subjective attraction meets objective attractiveness.',
  },
  {
    id: referenceId('hart-punishment-responsibility'),
    kind: 'book',
    authors: 'Hart, H. L. A.',
    year: 1968,
    title: 'Punishment and Responsibility: Essays in the Philosophy of Law',
    source: 'Oxford University Press',
    supports:
      'The separation of the general justifying aim of punishment from the principles limiting its distribution.',
  },
  {
    id: referenceId('duff-punishment-communication'),
    kind: 'book',
    authors: 'Duff, R. A.',
    year: 2001,
    title: 'Punishment, Communication, and Community',
    source: 'Oxford University Press',
    supports: 'Punishment understood as communication addressed to a member of a moral community.',
  },
  {
    id: referenceId('caruso-rejecting-retributivism'),
    kind: 'book',
    authors: 'Caruso, G. D.',
    year: 2021,
    title: 'Rejecting Retributivism: Free Will, Punishment, and Criminal Justice',
    source: 'Cambridge University Press',
    supports:
      'The public-health quarantine model: incapacitation justified by protection rather than by desert.',
  },
  {
    id: referenceId('rawls-theory-justice'),
    kind: 'book',
    authors: 'Rawls, J.',
    year: 1971,
    title: 'A Theory of Justice',
    source: 'Harvard University Press',
    supports:
      'The original position and the veil of ignorance; the claim that the distribution of natural talents is arbitrary from a moral point of view.',
  },
  {
    id: referenceId('korsgaard-sources-normativity'),
    kind: 'book',
    authors: 'Korsgaard, C. M.',
    year: 1996,
    title: 'The Sources of Normativity',
    source: 'Cambridge University Press',
    supports:
      'The constructivist answer to where obligation comes from, grounded in reflective self-endorsement.',
  },
  {
    id: referenceId('blackburn-ruling-passions'),
    kind: 'book',
    authors: 'Blackburn, S.',
    year: 1998,
    title: 'Ruling Passions: A Theory of Practical Reasoning',
    source: 'Oxford University Press',
    supports:
      'Quasi-realism: how moral talk can keep its ordinary form without objective moral facts behind it.',
  },
  {
    id: referenceId('shafer-landau-moral-realism'),
    kind: 'book',
    authors: 'Shafer-Landau, R.',
    year: 2003,
    title: 'Moral Realism: A Defence',
    source: 'Oxford University Press',
    supports: 'A contemporary non-naturalist defence of mind-independent moral facts.',
  },
  {
    id: referenceId('enoch-taking-morality-seriously'),
    kind: 'book',
    authors: 'Enoch, D.',
    year: 2011,
    title: 'Taking Morality Seriously: A Defense of Robust Realism',
    source: 'Oxford University Press',
    supports: 'The indispensability argument for irreducibly normative truths.',
  },
  {
    id: referenceId('street-2006-darwinian-dilemma'),
    kind: 'journal-article',
    authors: 'Street, S.',
    year: 2006,
    title: 'A Darwinian Dilemma for Realist Theories of Value',
    source: 'Philosophical Studies 127, 109–166',
    doi: '10.1007/s11098-005-1726-6',
    supports:
      'The evolutionary debunking argument, and the realist replies it was designed to pre-empt.',
  },
  {
    id: referenceId('singer-1972-famine'),
    kind: 'book',
    authors: 'Singer, P.',
    year: 2016,
    title: 'Famine, Affluence, and Morality',
    source:
      'Oxford University Press (essay first published in Philosophy & Public Affairs 1, 1972)',
    supports:
      'The argument that distance makes no moral difference, used here as a case where a principle outruns intuition.',
  },
  {
    id: referenceId('foot-1967-double-effect'),
    kind: 'book',
    authors: 'Foot, P.',
    year: 2002,
    title:
      'The Problem of Abortion and the Doctrine of the Double Effect, in Virtues and Vices and Other Essays in Moral Philosophy',
    source: 'Oxford University Press (essay first published in Oxford Review 5, 1967)',
    supports: 'The original trolley case, introduced to test a distinction rather than to poll it.',
  },
  {
    id: referenceId('thomson-1976-trolley'),
    kind: 'journal-article',
    authors: 'Thomson, J. J.',
    year: 1976,
    title: 'Killing, Letting Die, and the Trolley Problem',
    source: 'The Monist 59, 204–217',
    doi: '10.5840/monist197659224',
    supports:
      'The footbridge variant and the pressure it puts on a purely consequentialist answer.',
  },
  {
    id: referenceId('doris-lack-of-character'),
    kind: 'book',
    authors: 'Doris, J. M.',
    year: 2002,
    title: 'Lack of Character: Personality and Moral Behavior',
    source: 'Cambridge University Press',
    supports:
      'The situationist challenge to global character traits, and what it does and does not imply for virtue ethics.',
  },
  {
    id: referenceId('berlin-two-concepts'),
    kind: 'book',
    authors: 'Berlin, I.',
    year: 1969,
    title: 'Two Concepts of Liberty, in Four Essays on Liberty',
    source: 'Oxford University Press (lecture delivered 1958)',
    supports: 'Negative and positive liberty as distinct questions often run together.',
  },

  /* ------------------------------------- empirical work cited as empirical */
  {
    id: referenceId('libet-1983-readiness-potential'),
    kind: 'journal-article',
    authors: 'Libet, B., Gleason, C. A., Wright, E. W. & Pearl, D. K.',
    year: 1983,
    title:
      'Time of conscious intention to act in relation to onset of cerebral activity (readiness-potential)',
    source: 'Brain 106, 623–642',
    doi: '10.1093/brain/106.3.623',
    supports:
      'The reported gap between readiness-potential onset and the timed awareness of an urge to move.',
  },
  {
    id: referenceId('schurger-2012-accumulator'),
    kind: 'journal-article',
    authors: 'Schurger, A., Sitt, J. D. & Dehaene, S.',
    year: 2012,
    title: 'An accumulator model for spontaneous neural activity prior to self-initiated movement',
    source: 'PNAS 109, E2904–E2913',
    doi: '10.1073/pnas.1210467109',
    supports:
      'The alternative reading of the readiness potential as an artefact of averaging fluctuating activity.',
  },
  {
    id: referenceId('mele-effective-intentions'),
    kind: 'book',
    authors: 'Mele, A. R.',
    year: 2009,
    title: 'Effective Intentions: The Power of Conscious Will',
    source: 'Oxford University Press',
    supports:
      'The philosophical critique of what the Libet paradigm can establish about decisions.',
  },
  {
    id: referenceId('milgram-1963-obedience'),
    kind: 'journal-article',
    authors: 'Milgram, S.',
    year: 1963,
    title: 'Behavioral Study of Obedience',
    source: 'Journal of Abnormal and Social Psychology 67, 371–378',
    doi: '10.1037/h0040525',
    supports:
      'Compliance far exceeding what observers predicted, cited here for the prediction gap rather than for a rate.',
  },
  {
    id: referenceId('darley-batson-1973-jerusalem'),
    kind: 'journal-article',
    authors: 'Darley, J. M. & Batson, C. D.',
    year: 1973,
    title:
      '“From Jerusalem to Jericho”: A study of situational and dispositional variables in helping behavior',
    source: 'Journal of Personality and Social Psychology 27, 100–108',
    doi: '10.1037/h0034449',
    supports: 'Hurry affecting helping more than the content of what the person had been thinking.',
  },
  {
    id: referenceId('haidt-2001-emotional-dog'),
    kind: 'journal-article',
    authors: 'Haidt, J.',
    year: 2001,
    title:
      'The emotional dog and its rational tail: A social intuitionist approach to moral judgment',
    source: 'Psychological Review 108, 814–834',
    doi: '10.1037/0033-295X.108.4.814',
    supports:
      'The proposal that moral reasoning often follows judgement, and the debate that proposal opened.',
  },
  {
    id: referenceId('nisbett-wilson-1977-telling-more'),
    kind: 'journal-article',
    authors: 'Nisbett, R. E. & Wilson, T. D.',
    year: 1977,
    title: 'Telling more than we can know: Verbal reports on mental processes',
    source: 'Psychological Review 84, 231–259',
    doi: '10.1037/0033-295X.84.3.231',
    supports:
      'Confident reports about one’s own reasons that did not match the manipulated cause of the behaviour.',
  },

  /* ------------------------------------------- surveys of live disputes */
  {
    id: referenceId('sep-identity-personal'),
    kind: 'encyclopedia',
    authors: 'Olson, E. T.',
    year: 2023,
    title: 'Personal Identity',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/identity-personal/',
    accessed: SEP_ACCESSED,
    supports: 'The competing criteria — psychological, biological, narrative — and their problems.',
  },
  {
    id: referenceId('sep-identity-ethics'),
    kind: 'encyclopedia',
    authors: 'Shoemaker, D.',
    year: 2021,
    title: 'Personal Identity and Ethics',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/identity-ethics/',
    accessed: SEP_ACCESSED,
    supports: 'What turns on identity in practice: promises, desert, compensation, anticipation.',
  },
  {
    id: referenceId('sep-freewill'),
    kind: 'encyclopedia',
    authors: 'O’Connor, T. & Franklin, C.',
    year: 2022,
    title: 'Free Will',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/freewill/',
    accessed: SEP_ACCESSED,
    supports: 'The map of positions and the state of the dispute.',
  },
  {
    id: referenceId('sep-compatibilism'),
    kind: 'encyclopedia',
    authors: 'McKenna, M. & Coates, D. J.',
    year: 2024,
    title: 'Compatibilism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/compatibilism/',
    accessed: SEP_ACCESSED,
    supports: 'Classical and contemporary compatibilist strategies and the standard objections.',
  },
  {
    id: referenceId('sep-incompatibilism-arguments'),
    kind: 'encyclopedia',
    authors: 'Kane, R.',
    year: 2023,
    title: 'Arguments for Incompatibilism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/incompatibilism-arguments/',
    accessed: SEP_ACCESSED,
    supports: 'The consequence argument and the luck objection to libertarian views.',
  },
  {
    id: referenceId('sep-determinism-causal'),
    kind: 'encyclopedia',
    authors: 'Hoefer, C.',
    year: 2023,
    title: 'Causal Determinism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/determinism-causal/',
    accessed: SEP_ACCESSED,
    supports:
      'Why determinism is harder to state precisely than it looks, and why physics has not settled it.',
  },
  {
    id: referenceId('sep-moral-responsibility'),
    kind: 'encyclopedia',
    authors: 'Talbert, M.',
    year: 2024,
    title: 'Moral Responsibility',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/moral-responsibility/',
    accessed: SEP_ACCESSED,
    supports: 'Conditions on responsibility, and the varieties of exemption and excuse.',
  },
  {
    id: referenceId('sep-moral-luck'),
    kind: 'encyclopedia',
    authors: 'Nelkin, D. K.',
    year: 2023,
    title: 'Moral Luck',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/moral-luck/',
    accessed: SEP_ACCESSED,
    supports: 'The four kinds of moral luck and the range of responses to the paradox.',
  },
  {
    id: referenceId('sep-moral-realism'),
    kind: 'encyclopedia',
    authors: 'Sayre-McCord, G.',
    year: 2023,
    title: 'Moral Realism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/moral-realism/',
    accessed: SEP_ACCESSED,
    supports: 'What realism commits one to, and the main lines of argument for it.',
  },
  {
    id: referenceId('sep-moral-anti-realism'),
    kind: 'encyclopedia',
    authors: 'Joyce, R.',
    year: 2021,
    title: 'Moral Anti-Realism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/moral-anti-realism/',
    accessed: SEP_ACCESSED,
    supports: 'Error theory, expressivism and relativism distinguished from one another.',
  },
  {
    id: referenceId('sep-naturalism-moral'),
    kind: 'encyclopedia',
    authors: 'Lutz, M. & Lenman, J.',
    year: 2021,
    title: 'Moral Naturalism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/naturalism-moral/',
    accessed: SEP_ACCESSED,
    supports:
      'Naturalist attempts to bridge the is–ought gap, and why the open-question argument is no longer treated as decisive.',
  },
  {
    id: referenceId('sep-hume-moral'),
    kind: 'encyclopedia',
    authors: 'Cohon, R.',
    year: 2018,
    title: 'Hume’s Moral Philosophy',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/hume-moral/',
    accessed: SEP_ACCESSED,
    supports:
      'The scholarly dispute over how strong a conclusion the is–ought paragraph actually supports.',
  },
  {
    id: referenceId('sep-consciousness'),
    kind: 'encyclopedia',
    authors: 'Van Gulick, R.',
    year: 2022,
    title: 'Consciousness',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/consciousness/',
    accessed: SEP_ACCESSED,
    supports: 'The senses of “consciousness”, and the range of theories on offer.',
  },
  {
    id: referenceId('sep-qualia'),
    kind: 'encyclopedia',
    authors: 'Tye, M.',
    year: 2021,
    title: 'Qualia',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/qualia/',
    accessed: SEP_ACCESSED,
    supports: 'What is being asserted when experience is said to have a felt quality.',
  },
  {
    id: referenceId('sep-zombies'),
    kind: 'encyclopedia',
    authors: 'Kirk, R.',
    year: 2023,
    title: 'Zombies',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/zombies/',
    accessed: SEP_ACCESSED,
    supports: 'The conceivability argument and the replies that deny the inference to possibility.',
  },
  {
    id: referenceId('sep-other-minds'),
    kind: 'encyclopedia',
    authors: 'Avramides, A.',
    year: 2023,
    title: 'Other Minds',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/other-minds/',
    accessed: SEP_ACCESSED,
    supports: 'Why the inference to other minds is harder to justify than it is to make.',
  },
  {
    id: referenceId('sep-panpsychism'),
    kind: 'encyclopedia',
    authors: 'Goff, P., Seager, W. & Allen-Hermanson, S.',
    year: 2022,
    title: 'Panpsychism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/panpsychism/',
    accessed: SEP_ACCESSED,
    supports: 'The position, its motivation from the hard problem, and the combination problem.',
  },
  {
    id: referenceId('sep-mind-indian-buddhism'),
    kind: 'encyclopedia',
    authors: 'Coseru, C.',
    year: 2022,
    title: 'Mind in Indian Buddhist Philosophy',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/mind-indian-buddhism/',
    accessed: SEP_ACCESSED,
    supports:
      'The philosophical content of anattā, including the explicit rejection of annihilationism.',
  },
  {
    id: referenceId('sep-nietzsche-moral-political'),
    kind: 'encyclopedia',
    authors: 'Leiter, B.',
    year: 2021,
    title: 'Nietzsche’s Moral and Political Philosophy',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/nietzsche-moral-political/',
    accessed: SEP_ACCESSED,
    supports:
      'Scholarly reading of the critique of morality, and correction of popular misreadings of the Übermensch.',
  },
  {
    id: referenceId('sep-existentialism'),
    kind: 'encyclopedia',
    authors: 'Aho, K.',
    year: 2023,
    title: 'Existentialism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/existentialism/',
    accessed: SEP_ACCESSED,
    supports:
      'The differences among thinkers grouped under the label, including those who rejected it.',
  },
  {
    id: referenceId('sep-life-meaning'),
    kind: 'encyclopedia',
    authors: 'Metz, T.',
    year: 2023,
    title: 'The Meaning of Life',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/life-meaning/',
    accessed: SEP_ACCESSED,
    supports: 'Supernaturalist, objective naturalist, subjective and hybrid accounts of meaning.',
  },
  {
    id: referenceId('sep-legal-punishment'),
    kind: 'encyclopedia',
    authors: 'Duff, R. A. & Hoskins, Z.',
    year: 2022,
    title: 'Legal Punishment',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/legal-punishment/',
    accessed: SEP_ACCESSED,
    supports:
      'Retributive, consequentialist, communicative and mixed justifications of punishment.',
  },
  {
    id: referenceId('sep-ethics-virtue'),
    kind: 'encyclopedia',
    authors: 'Hursthouse, R. & Pettigrove, G.',
    year: 2023,
    title: 'Virtue Ethics',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/ethics-virtue/',
    accessed: SEP_ACCESSED,
    supports: 'The structure of virtue ethics and the situationist objection to it.',
  },
  {
    id: referenceId('sep-kant-transcendental-idealism'),
    kind: 'encyclopedia',
    authors: 'Stang, N. F.',
    year: 2022,
    title: 'Kant’s Transcendental Idealism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/kant-transcendental-idealism/',
    accessed: SEP_ACCESSED,
    supports:
      'Competing interpretations of the appearance/thing-in-itself distinction, which is itself contested.',
  },
  {
    id: referenceId('sep-descartes-epistemology'),
    kind: 'encyclopedia',
    authors: 'Newman, L.',
    year: 2023,
    title: 'Descartes’ Epistemology',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/descartes-epistemology/',
    accessed: SEP_ACCESSED,
    supports: 'The structure of the doubt, and the standard objections to what the cogito secures.',
  },
  {
    id: referenceId('sep-induction-problem'),
    kind: 'encyclopedia',
    authors: 'Henderson, L.',
    year: 2022,
    title: 'The Problem of Induction',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/induction-problem/',
    accessed: SEP_ACCESSED,
    supports: 'Hume’s argument, and why no reply is generally accepted as a solution.',
  },
  {
    id: referenceId('sep-personal-autonomy'),
    kind: 'encyclopedia',
    authors: 'Buss, S. & Westlund, A.',
    year: 2018,
    title: 'Personal Autonomy',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/personal-autonomy/',
    accessed: SEP_ACCESSED,
    supports:
      'Procedural and substantive accounts of when a desire counts as the agent’s own, and the manipulation problem.',
  },
  {
    id: referenceId('sep-skepticism'),
    kind: 'encyclopedia',
    authors: 'Comesaña, J. & Klein, P.',
    year: 2024,
    title: 'Skepticism',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/skepticism/',
    accessed: SEP_ACCESSED,
    supports: 'The structure of sceptical arguments and the main responses to them.',
  },
  {
    id: referenceId('sep-well-being'),
    kind: 'encyclopedia',
    authors: 'Crisp, R.',
    year: 2021,
    title: 'Well-Being',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/well-being/',
    accessed: SEP_ACCESSED,
    supports:
      'Hedonist, desire-satisfaction and objective-list theories, and why meaning and well-being come apart.',
  },
  {
    id: referenceId('sep-death'),
    kind: 'encyclopedia',
    authors: 'Luper, S.',
    year: 2021,
    title: 'Death',
    source: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/death/',
    accessed: SEP_ACCESSED,
    supports: 'The Epicurean argument that death is not a harm, and the deprivation replies to it.',
  },
];
